// Auto-generated by tools/generate-levels.mjs — do not edit by hand.
// Every level is verified solvable by src/solver.js at generation time.
export const LEVELS = [
 {
  "name": "First Light",
  "gridWidth": 6,
  "gridHeight": 6,
  "obstacles": [],
  "ships": [
   {
    "x": 1,
    "y": 2,
    "direction": "N",
    "length": 1
   },
   {
    "x": 4,
    "y": 0,
    "direction": "S",
    "length": 3
   },
   {
    "x": 0,
    "y": 0,
    "direction": "S",
    "length": 1
   },
   {
    "x": 3,
    "y": 5,
    "direction": "E",
    "length": 2
   }
  ]
 },
 {
  "name": "Gentle Tide",
  "gridWidth": 6,
  "gridHeight": 6,
  "obstacles": [],
  "ships": [
   {
    "x": 1,
    "y": 2,
    "direction": "W",
    "length": 2
   },
   {
    "x": 3,
    "y": 1,
    "direction": "E",
    "length": 2
   },
   {
    "x": 3,
    "y": 4,
    "direction": "W",
    "length": 1
   },
   {
    "x": 1,
    "y": 1,
    "direction": "E",
    "length": 2
   },
   {
    "x": 2,
    "y": 3,
    "direction": "W",
    "length": 3
   }
  ]
 },
 {
  "name": "Quiet Moorings",
  "gridWidth": 7,
  "gridHeight": 7,
  "obstacles": [],
  "ships": [
   {
    "x": 5,
    "y": 4,
    "direction": "W",
    "length": 2
   },
   {
    "x": 0,
    "y": 4,
    "direction": "S",
    "length": 2
   },
   {
    "x": 2,
    "y": 0,
    "direction": "S",
    "length": 3
   },
   {
    "x": 0,
    "y": 1,
    "direction": "N",
    "length": 2
   },
   {
    "x": 6,
    "y": 6,
    "direction": "E",
    "length": 1
   },
   {
    "x": 0,
    "y": 3,
    "direction": "E",
    "length": 2
   }
  ]
 },
 {
  "name": "Morning Ferry",
  "gridWidth": 7,
  "gridHeight": 7,
  "obstacles": [],
  "ships": [
   {
    "x": 1,
    "y": 3,
    "direction": "W",
    "length": 2
   },
   {
    "x": 1,
    "y": 4,
    "direction": "N",
    "length": 2
   },
   {
    "x": 3,
    "y": 5,
    "direction": "W",
    "length": 1
   },
   {
    "x": 5,
    "y": 0,
    "direction": "S",
    "length": 3
   },
   {
    "x": 3,
    "y": 1,
    "direction": "N",
    "length": 1
   },
   {
    "x": 3,
    "y": 0,
    "direction": "E",
    "length": 1
   },
   {
    "x": 4,
    "y": 4,
    "direction": "W",
    "length": 3
   },
   {
    "x": 0,
    "y": 1,
    "direction": "S",
    "length": 4
   }
  ]
 },
 {
  "name": "Fisherman's Return",
  "gridWidth": 8,
  "gridHeight": 8,
  "obstacles": [],
  "ships": [
   {
    "x": 4,
    "y": 6,
    "direction": "W",
    "length": 2
   },
   {
    "x": 0,
    "y": 6,
    "direction": "W",
    "length": 3
   },
   {
    "x": 2,
    "y": 4,
    "direction": "N",
    "length": 1
   },
   {
    "x": 6,
    "y": 2,
    "direction": "E",
    "length": 2
   },
   {
    "x": 4,
    "y": 2,
    "direction": "S",
    "length": 1
   },
   {
    "x": 5,
    "y": 1,
    "direction": "N",
    "length": 1
   },
   {
    "x": 4,
    "y": 4,
    "direction": "W",
    "length": 3
   },
   {
    "x": 0,
    "y": 0,
    "direction": "S",
    "length": 3
   },
   {
    "x": 3,
    "y": 0,
    "direction": "E",
    "length": 3
   },
   {
    "x": 2,
    "y": 1,
    "direction": "W",
    "length": 3
   }
  ]
 },
 {
  "name": "Crowded Quay",
  "gridWidth": 8,
  "gridHeight": 8,
  "obstacles": [
   {
    "x": 1,
    "y": 2,
    "type": "pier"
   }
  ],
  "ships": [
   {
    "x": 7,
    "y": 2,
    "direction": "S",
    "length": 3
   },
   {
    "x": 5,
    "y": 3,
    "direction": "E",
    "length": 2
   },
   {
    "x": 0,
    "y": 5,
    "direction": "N",
    "length": 1
   },
   {
    "x": 2,
    "y": 3,
    "direction": "E",
    "length": 1
   },
   {
    "x": 2,
    "y": 6,
    "direction": "N",
    "length": 1
   },
   {
    "x": 2,
    "y": 2,
    "direction": "E",
    "length": 3
   },
   {
    "x": 0,
    "y": 2,
    "direction": "N",
    "length": 3
   },
   {
    "x": 3,
    "y": 3,
    "direction": "E",
    "length": 1
   },
   {
    "x": 7,
    "y": 5,
    "direction": "W",
    "length": 1
   },
   {
    "x": 0,
    "y": 6,
    "direction": "E",
    "length": 1
   },
   {
    "x": 4,
    "y": 7,
    "direction": "W",
    "length": 1
   }
  ]
 },
 {
  "name": "The Narrows",
  "gridWidth": 8,
  "gridHeight": 8,
  "obstacles": [
   {
    "x": 5,
    "y": 2,
    "type": "pier"
   },
   {
    "x": 6,
    "y": 0,
    "type": "pier"
   }
  ],
  "ships": [
   {
    "x": 3,
    "y": 4,
    "direction": "E",
    "length": 1
   },
   {
    "x": 7,
    "y": 5,
    "direction": "S",
    "length": 2
   },
   {
    "x": 4,
    "y": 6,
    "direction": "W",
    "length": 2
   },
   {
    "x": 0,
    "y": 4,
    "direction": "E",
    "length": 2
   },
   {
    "x": 6,
    "y": 2,
    "direction": "E",
    "length": 2
   },
   {
    "x": 1,
    "y": 0,
    "direction": "W",
    "length": 3
   },
   {
    "x": 4,
    "y": 7,
    "direction": "N",
    "length": 1
   },
   {
    "x": 4,
    "y": 3,
    "direction": "N",
    "length": 3
   },
   {
    "x": 3,
    "y": 5,
    "direction": "N",
    "length": 2
   },
   {
    "x": 0,
    "y": 2,
    "direction": "W",
    "length": 3
   },
   {
    "x": 6,
    "y": 7,
    "direction": "W",
    "length": 2
   },
   {
    "x": 2,
    "y": 1,
    "direction": "E",
    "length": 3
   }
  ]
 },
 {
  "name": "Cargo Day",
  "gridWidth": 9,
  "gridHeight": 9,
  "obstacles": [
   {
    "x": 6,
    "y": 4,
    "type": "pier"
   },
   {
    "x": 1,
    "y": 1,
    "type": "rock"
   }
  ],
  "ships": [
   {
    "x": 4,
    "y": 1,
    "direction": "N",
    "length": 3
   },
   {
    "x": 2,
    "y": 6,
    "direction": "N",
    "length": 2
   },
   {
    "x": 5,
    "y": 0,
    "direction": "W",
    "length": 2
   },
   {
    "x": 5,
    "y": 3,
    "direction": "E",
    "length": 3
   },
   {
    "x": 4,
    "y": 4,
    "direction": "S",
    "length": 3
   },
   {
    "x": 8,
    "y": 0,
    "direction": "N",
    "length": 2
   },
   {
    "x": 2,
    "y": 0,
    "direction": "W",
    "length": 3
   },
   {
    "x": 0,
    "y": 7,
    "direction": "S",
    "length": 1
   },
   {
    "x": 5,
    "y": 5,
    "direction": "N",
    "length": 2
   },
   {
    "x": 6,
    "y": 6,
    "direction": "W",
    "length": 2
   },
   {
    "x": 0,
    "y": 0,
    "direction": "S",
    "length": 4
   },
   {
    "x": 7,
    "y": 7,
    "direction": "N",
    "length": 2
   },
   {
    "x": 2,
    "y": 5,
    "direction": "E",
    "length": 1
   },
   {
    "x": 3,
    "y": 5,
    "direction": "N",
    "length": 2
   }
  ]
 },
 {
  "name": "Buoy Garden",
  "gridWidth": 9,
  "gridHeight": 9,
  "obstacles": [
   {
    "x": 4,
    "y": 0,
    "type": "rock"
   },
   {
    "x": 2,
    "y": 2,
    "type": "buoy"
   },
   {
    "x": 7,
    "y": 7,
    "type": "rock"
   }
  ],
  "ships": [
   {
    "x": 8,
    "y": 3,
    "direction": "N",
    "length": 1
   },
   {
    "x": 6,
    "y": 6,
    "direction": "N",
    "length": 3
   },
   {
    "x": 3,
    "y": 1,
    "direction": "W",
    "length": 3
   },
   {
    "x": 3,
    "y": 5,
    "direction": "W",
    "length": 3
   },
   {
    "x": 2,
    "y": 3,
    "direction": "S",
    "length": 3
   },
   {
    "x": 7,
    "y": 4,
    "direction": "N",
    "length": 3
   },
   {
    "x": 0,
    "y": 1,
    "direction": "W",
    "length": 3
   },
   {
    "x": 0,
    "y": 4,
    "direction": "S",
    "length": 2
   },
   {
    "x": 6,
    "y": 4,
    "direction": "N",
    "length": 2
   },
   {
    "x": 8,
    "y": 5,
    "direction": "N",
    "length": 2
   },
   {
    "x": 7,
    "y": 0,
    "direction": "E",
    "length": 2
   },
   {
    "x": 2,
    "y": 8,
    "direction": "E",
    "length": 1
   },
   {
    "x": 5,
    "y": 2,
    "direction": "N",
    "length": 1
   },
   {
    "x": 6,
    "y": 1,
    "direction": "W",
    "length": 3
   },
   {
    "x": 0,
    "y": 0,
    "direction": "S",
    "length": 1
   }
  ]
 },
 {
  "name": "Slack Water",
  "gridWidth": 10,
  "gridHeight": 10,
  "obstacles": [
   {
    "x": 9,
    "y": 1,
    "type": "buoy"
   },
   {
    "x": 9,
    "y": 3,
    "type": "rock"
   },
   {
    "x": 5,
    "y": 2,
    "type": "rock"
   }
  ],
  "ships": [
   {
    "x": 1,
    "y": 0,
    "direction": "N",
    "length": 2
   },
   {
    "x": 5,
    "y": 9,
    "direction": "E",
    "length": 3
   },
   {
    "x": 1,
    "y": 7,
    "direction": "E",
    "length": 3
   },
   {
    "x": 4,
    "y": 5,
    "direction": "S",
    "length": 2
   },
   {
    "x": 0,
    "y": 6,
    "direction": "S",
    "length": 4
   },
   {
    "x": 7,
    "y": 5,
    "direction": "W",
    "length": 2
   },
   {
    "x": 7,
    "y": 2,
    "direction": "S",
    "length": 3
   },
   {
    "x": 2,
    "y": 8,
    "direction": "N",
    "length": 2
   },
   {
    "x": 1,
    "y": 2,
    "direction": "S",
    "length": 2
   },
   {
    "x": 3,
    "y": 0,
    "direction": "W",
    "length": 3
   },
   {
    "x": 3,
    "y": 3,
    "direction": "W",
    "length": 1
   },
   {
    "x": 2,
    "y": 3,
    "direction": "W",
    "length": 1
   },
   {
    "x": 0,
    "y": 4,
    "direction": "E",
    "length": 3
   },
   {
    "x": 7,
    "y": 6,
    "direction": "E",
    "length": 3
   },
   {
    "x": 8,
    "y": 7,
    "direction": "N",
    "length": 3
   },
   {
    "x": 2,
    "y": 5,
    "direction": "W",
    "length": 2
   }
  ]
 },
 {
  "name": "Rush at the Docks",
  "gridWidth": 10,
  "gridHeight": 10,
  "obstacles": [
   {
    "x": 5,
    "y": 8,
    "type": "pier"
   },
   {
    "x": 0,
    "y": 7,
    "type": "rock"
   },
   {
    "x": 8,
    "y": 0,
    "type": "pier"
   },
   {
    "x": 4,
    "y": 9,
    "type": "rock"
   }
  ],
  "ships": [
   {
    "x": 6,
    "y": 6,
    "direction": "W",
    "length": 3
   },
   {
    "x": 6,
    "y": 2,
    "direction": "W",
    "length": 4
   },
   {
    "x": 2,
    "y": 9,
    "direction": "W",
    "length": 2
   },
   {
    "x": 2,
    "y": 3,
    "direction": "E",
    "length": 4
   },
   {
    "x": 0,
    "y": 8,
    "direction": "S",
    "length": 2
   },
   {
    "x": 9,
    "y": 7,
    "direction": "N",
    "length": 3
   },
   {
    "x": 9,
    "y": 4,
    "direction": "N",
    "length": 2
   },
   {
    "x": 2,
    "y": 4,
    "direction": "S",
    "length": 3
   },
   {
    "x": 0,
    "y": 4,
    "direction": "N",
    "length": 1
   },
   {
    "x": 6,
    "y": 7,
    "direction": "E",
    "length": 2
   },
   {
    "x": 3,
    "y": 6,
    "direction": "W",
    "length": 1
   },
   {
    "x": 4,
    "y": 5,
    "direction": "E",
    "length": 3
   },
   {
    "x": 1,
    "y": 7,
    "direction": "E",
    "length": 4
   },
   {
    "x": 9,
    "y": 6,
    "direction": "N",
    "length": 1
   },
   {
    "x": 2,
    "y": 8,
    "direction": "W",
    "length": 2
   },
   {
    "x": 5,
    "y": 9,
    "direction": "S",
    "length": 1
   },
   {
    "x": 0,
    "y": 1,
    "direction": "N",
    "length": 2
   },
   {
    "x": 6,
    "y": 8,
    "direction": "E",
    "length": 1
   }
  ]
 },
 {
  "name": "Tangled Lanes",
  "gridWidth": 10,
  "gridHeight": 10,
  "obstacles": [
   {
    "x": 8,
    "y": 8,
    "type": "rock"
   },
   {
    "x": 4,
    "y": 2,
    "type": "rock"
   },
   {
    "x": 2,
    "y": 3,
    "type": "buoy"
   },
   {
    "x": 2,
    "y": 5,
    "type": "buoy"
   }
  ],
  "ships": [
   {
    "x": 8,
    "y": 4,
    "direction": "N",
    "length": 4
   },
   {
    "x": 9,
    "y": 2,
    "direction": "E",
    "length": 1
   },
   {
    "x": 3,
    "y": 0,
    "direction": "S",
    "length": 2
   },
   {
    "x": 7,
    "y": 4,
    "direction": "N",
    "length": 4
   },
   {
    "x": 9,
    "y": 7,
    "direction": "N",
    "length": 2
   },
   {
    "x": 0,
    "y": 1,
    "direction": "W",
    "length": 3
   },
   {
    "x": 4,
    "y": 9,
    "direction": "W",
    "length": 4
   },
   {
    "x": 6,
    "y": 2,
    "direction": "E",
    "length": 3
   },
   {
    "x": 2,
    "y": 6,
    "direction": "E",
    "length": 4
   },
   {
    "x": 3,
    "y": 7,
    "direction": "S",
    "length": 3
   },
   {
    "x": 0,
    "y": 8,
    "direction": "W",
    "length": 2
   },
   {
    "x": 1,
    "y": 0,
    "direction": "N",
    "length": 1
   },
   {
    "x": 1,
    "y": 4,
    "direction": "E",
    "length": 2
   },
   {
    "x": 3,
    "y": 5,
    "direction": "E",
    "length": 2
   },
   {
    "x": 5,
    "y": 1,
    "direction": "E",
    "length": 3
   },
   {
    "x": 1,
    "y": 9,
    "direction": "N",
    "length": 1
   },
   {
    "x": 6,
    "y": 5,
    "direction": "S",
    "length": 3
   },
   {
    "x": 0,
    "y": 2,
    "direction": "N",
    "length": 3
   },
   {
    "x": 5,
    "y": 5,
    "direction": "S",
    "length": 1
   },
   {
    "x": 1,
    "y": 2,
    "direction": "W",
    "length": 1
   }
  ]
 },
 {
  "name": "Old Pier",
  "gridWidth": 11,
  "gridHeight": 11,
  "obstacles": [
   {
    "x": 7,
    "y": 2,
    "type": "pier"
   },
   {
    "x": 1,
    "y": 2,
    "type": "buoy"
   },
   {
    "x": 1,
    "y": 5,
    "type": "pier"
   },
   {
    "x": 7,
    "y": 4,
    "type": "rock"
   },
   {
    "x": 3,
    "y": 5,
    "type": "buoy"
   }
  ],
  "ships": [
   {
    "x": 9,
    "y": 1,
    "direction": "S",
    "length": 4
   },
   {
    "x": 7,
    "y": 0,
    "direction": "E",
    "length": 2
   },
   {
    "x": 4,
    "y": 4,
    "direction": "W",
    "length": 3
   },
   {
    "x": 5,
    "y": 8,
    "direction": "W",
    "length": 2
   },
   {
    "x": 1,
    "y": 6,
    "direction": "E",
    "length": 2
   },
   {
    "x": 1,
    "y": 9,
    "direction": "S",
    "length": 2
   },
   {
    "x": 0,
    "y": 0,
    "direction": "W",
    "length": 4
   },
   {
    "x": 2,
    "y": 1,
    "direction": "E",
    "length": 2
   },
   {
    "x": 0,
    "y": 3,
    "direction": "S",
    "length": 3
   },
   {
    "x": 8,
    "y": 9,
    "direction": "S",
    "length": 2
   },
   {
    "x": 2,
    "y": 9,
    "direction": "E",
    "length": 2
   },
   {
    "x": 10,
    "y": 9,
    "direction": "N",
    "length": 1
   },
   {
    "x": 2,
    "y": 8,
    "direction": "N",
    "length": 1
   },
   {
    "x": 5,
    "y": 1,
    "direction": "N",
    "length": 3
   },
   {
    "x": 7,
    "y": 1,
    "direction": "E",
    "length": 1
   },
   {
    "x": 8,
    "y": 6,
    "direction": "N",
    "length": 3
   },
   {
    "x": 0,
    "y": 7,
    "direction": "S",
    "length": 4
   },
   {
    "x": 1,
    "y": 7,
    "direction": "E",
    "length": 3
   },
   {
    "x": 2,
    "y": 3,
    "direction": "N",
    "length": 2
   },
   {
    "x": 10,
    "y": 8,
    "direction": "W",
    "length": 1
   },
   {
    "x": 10,
    "y": 4,
    "direction": "N",
    "length": 2
   },
   {
    "x": 2,
    "y": 10,
    "direction": "E",
    "length": 4
   }
  ]
 },
 {
  "name": "Harvest Fleet",
  "gridWidth": 11,
  "gridHeight": 11,
  "obstacles": [
   {
    "x": 9,
    "y": 9,
    "type": "buoy"
   },
   {
    "x": 10,
    "y": 5,
    "type": "buoy"
   },
   {
    "x": 1,
    "y": 10,
    "type": "buoy"
   },
   {
    "x": 9,
    "y": 8,
    "type": "buoy"
   },
   {
    "x": 4,
    "y": 4,
    "type": "buoy"
   }
  ],
  "ships": [
   {
    "x": 6,
    "y": 6,
    "direction": "W",
    "length": 3
   },
   {
    "x": 4,
    "y": 1,
    "direction": "W",
    "length": 1
   },
   {
    "x": 10,
    "y": 10,
    "direction": "E",
    "length": 1
   },
   {
    "x": 10,
    "y": 2,
    "direction": "N",
    "length": 2
   },
   {
    "x": 1,
    "y": 3,
    "direction": "E",
    "length": 2
   },
   {
    "x": 8,
    "y": 0,
    "direction": "E",
    "length": 1
   },
   {
    "x": 2,
    "y": 5,
    "direction": "S",
    "length": 4
   },
   {
    "x": 4,
    "y": 3,
    "direction": "E",
    "length": 2
   },
   {
    "x": 3,
    "y": 0,
    "direction": "E",
    "length": 2
   },
   {
    "x": 8,
    "y": 8,
    "direction": "S",
    "length": 1
   },
   {
    "x": 6,
    "y": 4,
    "direction": "E",
    "length": 3
   },
   {
    "x": 2,
    "y": 9,
    "direction": "W",
    "length": 4
   },
   {
    "x": 1,
    "y": 4,
    "direction": "N",
    "length": 2
   },
   {
    "x": 5,
    "y": 7,
    "direction": "S",
    "length": 1
   },
   {
    "x": 3,
    "y": 5,
    "direction": "W",
    "length": 1
   },
   {
    "x": 10,
    "y": 0,
    "direction": "N",
    "length": 1
   },
   {
    "x": 9,
    "y": 0,
    "direction": "E",
    "length": 1
   },
   {
    "x": 6,
    "y": 3,
    "direction": "E",
    "length": 1
   },
   {
    "x": 0,
    "y": 10,
    "direction": "W",
    "length": 1
   },
   {
    "x": 9,
    "y": 5,
    "direction": "N",
    "length": 1
   },
   {
    "x": 7,
    "y": 3,
    "direction": "E",
    "length": 2
   },
   {
    "x": 3,
    "y": 2,
    "direction": "S",
    "length": 1
   },
   {
    "x": 1,
    "y": 8,
    "direction": "N",
    "length": 1
   },
   {
    "x": 5,
    "y": 0,
    "direction": "S",
    "length": 2
   }
  ]
 },
 {
  "name": "Crossing Paths",
  "gridWidth": 12,
  "gridHeight": 12,
  "obstacles": [
   {
    "x": 1,
    "y": 5,
    "type": "rock"
   },
   {
    "x": 2,
    "y": 3,
    "type": "pier"
   },
   {
    "x": 2,
    "y": 7,
    "type": "buoy"
   },
   {
    "x": 10,
    "y": 0,
    "type": "buoy"
   },
   {
    "x": 2,
    "y": 4,
    "type": "rock"
   },
   {
    "x": 6,
    "y": 0,
    "type": "buoy"
   }
  ],
  "ships": [
   {
    "x": 6,
    "y": 2,
    "direction": "E",
    "length": 4
   },
   {
    "x": 5,
    "y": 6,
    "direction": "W",
    "length": 1
   },
   {
    "x": 4,
    "y": 10,
    "direction": "W",
    "length": 4
   },
   {
    "x": 7,
    "y": 9,
    "direction": "S",
    "length": 1
   },
   {
    "x": 0,
    "y": 2,
    "direction": "N",
    "length": 3
   },
   {
    "x": 4,
    "y": 1,
    "direction": "W",
    "length": 4
   },
   {
    "x": 8,
    "y": 9,
    "direction": "W",
    "length": 1
   },
   {
    "x": 3,
    "y": 1,
    "direction": "S",
    "length": 4
   },
   {
    "x": 0,
    "y": 5,
    "direction": "N",
    "length": 3
   },
   {
    "x": 5,
    "y": 7,
    "direction": "E",
    "length": 4
   },
   {
    "x": 10,
    "y": 5,
    "direction": "S",
    "length": 3
   },
   {
    "x": 6,
    "y": 3,
    "direction": "E",
    "length": 1
   },
   {
    "x": 8,
    "y": 3,
    "direction": "N",
    "length": 3
   },
   {
    "x": 3,
    "y": 8,
    "direction": "W",
    "length": 3
   },
   {
    "x": 9,
    "y": 8,
    "direction": "E",
    "length": 3
   },
   {
    "x": 6,
    "y": 4,
    "direction": "S",
    "length": 3
   },
   {
    "x": 5,
    "y": 0,
    "direction": "W",
    "length": 1
   },
   {
    "x": 2,
    "y": 6,
    "direction": "W",
    "length": 1
   },
   {
    "x": 11,
    "y": 10,
    "direction": "N",
    "length": 2
   },
   {
    "x": 10,
    "y": 2,
    "direction": "S",
    "length": 3
   },
   {
    "x": 7,
    "y": 6,
    "direction": "E",
    "length": 3
   },
   {
    "x": 3,
    "y": 9,
    "direction": "W",
    "length": 3
   },
   {
    "x": 10,
    "y": 9,
    "direction": "W",
    "length": 2
   },
   {
    "x": 7,
    "y": 11,
    "direction": "W",
    "length": 2
   },
   {
    "x": 0,
    "y": 11,
    "direction": "W",
    "length": 4
   },
   {
    "x": 4,
    "y": 2,
    "direction": "N",
    "length": 4
   }
  ]
 },
 {
  "name": "Full Berth",
  "gridWidth": 12,
  "gridHeight": 12,
  "obstacles": [
   {
    "x": 0,
    "y": 6,
    "type": "pier"
   },
   {
    "x": 5,
    "y": 0,
    "type": "rock"
   },
   {
    "x": 11,
    "y": 1,
    "type": "pier"
   },
   {
    "x": 5,
    "y": 2,
    "type": "buoy"
   },
   {
    "x": 1,
    "y": 3,
    "type": "buoy"
   },
   {
    "x": 0,
    "y": 2,
    "type": "rock"
   }
  ],
  "ships": [
   {
    "x": 10,
    "y": 7,
    "direction": "N",
    "length": 2
   },
   {
    "x": 1,
    "y": 9,
    "direction": "E",
    "length": 3
   },
   {
    "x": 7,
    "y": 6,
    "direction": "S",
    "length": 4
   },
   {
    "x": 7,
    "y": 1,
    "direction": "N",
    "length": 3
   },
   {
    "x": 3,
    "y": 4,
    "direction": "N",
    "length": 3
   },
   {
    "x": 4,
    "y": 3,
    "direction": "N",
    "length": 4
   },
   {
    "x": 5,
    "y": 5,
    "direction": "W",
    "length": 2
   },
   {
    "x": 1,
    "y": 7,
    "direction": "S",
    "length": 2
   },
   {
    "x": 4,
    "y": 8,
    "direction": "S",
    "length": 3
   },
   {
    "x": 2,
    "y": 1,
    "direction": "S",
    "length": 1
   },
   {
    "x": 8,
    "y": 11,
    "direction": "E",
    "length": 4
   },
   {
    "x": 1,
    "y": 10,
    "direction": "W",
    "length": 2
   },
   {
    "x": 10,
    "y": 2,
    "direction": "N",
    "length": 3
   },
   {
    "x": 4,
    "y": 7,
    "direction": "E",
    "length": 1
   },
   {
    "x": 3,
    "y": 11,
    "direction": "S",
    "length": 1
   },
   {
    "x": 6,
    "y": 4,
    "direction": "W",
    "length": 2
   },
   {
    "x": 6,
    "y": 10,
    "direction": "E",
    "length": 3
   },
   {
    "x": 3,
    "y": 1,
    "direction": "N",
    "length": 2
   },
   {
    "x": 4,
    "y": 11,
    "direction": "W",
    "length": 1
   },
   {
    "x": 10,
    "y": 0,
    "direction": "E",
    "length": 2
   },
   {
    "x": 9,
    "y": 0,
    "direction": "S",
    "length": 2
   },
   {
    "x": 10,
    "y": 6,
    "direction": "E",
    "length": 1
   },
   {
    "x": 8,
    "y": 2,
    "direction": "S",
    "length": 4
   },
   {
    "x": 6,
    "y": 6,
    "direction": "N",
    "length": 2
   },
   {
    "x": 9,
    "y": 8,
    "direction": "W",
    "length": 1
   },
   {
    "x": 7,
    "y": 0,
    "direction": "E",
    "length": 1
   },
   {
    "x": 11,
    "y": 2,
    "direction": "E",
    "length": 1
   },
   {
    "x": 6,
    "y": 2,
    "direction": "E",
    "length": 1
   }
  ]
 },
 {
  "name": "Patient Water",
  "gridWidth": 12,
  "gridHeight": 12,
  "obstacles": [
   {
    "x": 3,
    "y": 8,
    "type": "rock"
   },
   {
    "x": 1,
    "y": 10,
    "type": "rock"
   },
   {
    "x": 11,
    "y": 9,
    "type": "buoy"
   },
   {
    "x": 0,
    "y": 3,
    "type": "buoy"
   },
   {
    "x": 9,
    "y": 7,
    "type": "pier"
   },
   {
    "x": 8,
    "y": 10,
    "type": "rock"
   },
   {
    "x": 7,
    "y": 7,
    "type": "pier"
   }
  ],
  "ships": [
   {
    "x": 3,
    "y": 1,
    "direction": "E",
    "length": 3
   },
   {
    "x": 3,
    "y": 4,
    "direction": "N",
    "length": 1
   },
   {
    "x": 2,
    "y": 0,
    "direction": "W",
    "length": 4
   },
   {
    "x": 5,
    "y": 8,
    "direction": "E",
    "length": 3
   },
   {
    "x": 8,
    "y": 1,
    "direction": "E",
    "length": 3
   },
   {
    "x": 5,
    "y": 7,
    "direction": "W",
    "length": 1
   },
   {
    "x": 11,
    "y": 2,
    "direction": "N",
    "length": 4
   },
   {
    "x": 9,
    "y": 11,
    "direction": "E",
    "length": 1
   },
   {
    "x": 2,
    "y": 7,
    "direction": "S",
    "length": 3
   },
   {
    "x": 6,
    "y": 4,
    "direction": "W",
    "length": 1
   },
   {
    "x": 4,
    "y": 8,
    "direction": "N",
    "length": 4
   },
   {
    "x": 0,
    "y": 5,
    "direction": "E",
    "length": 3
   },
   {
    "x": 5,
    "y": 3,
    "direction": "E",
    "length": 2
   },
   {
    "x": 6,
    "y": 5,
    "direction": "E",
    "length": 3
   },
   {
    "x": 10,
    "y": 8,
    "direction": "N",
    "length": 2
   },
   {
    "x": 11,
    "y": 7,
    "direction": "N",
    "length": 1
   },
   {
    "x": 0,
    "y": 2,
    "direction": "W",
    "length": 4
   },
   {
    "x": 11,
    "y": 0,
    "direction": "N",
    "length": 1
   },
   {
    "x": 4,
    "y": 4,
    "direction": "N",
    "length": 2
   },
   {
    "x": 0,
    "y": 6,
    "direction": "W",
    "length": 4
   },
   {
    "x": 5,
    "y": 10,
    "direction": "N",
    "length": 2
   },
   {
    "x": 2,
    "y": 1,
    "direction": "W",
    "length": 1
   },
   {
    "x": 11,
    "y": 11,
    "direction": "E",
    "length": 1
   },
   {
    "x": 4,
    "y": 6,
    "direction": "W",
    "length": 4
   },
   {
    "x": 8,
    "y": 6,
    "direction": "W",
    "length": 2
   },
   {
    "x": 7,
    "y": 11,
    "direction": "E",
    "length": 2
   },
   {
    "x": 8,
    "y": 4,
    "direction": "W",
    "length": 2
   },
   {
    "x": 10,
    "y": 4,
    "direction": "W",
    "length": 1
   },
   {
    "x": 0,
    "y": 7,
    "direction": "W",
    "length": 2
   },
   {
    "x": 5,
    "y": 9,
    "direction": "W",
    "length": 3
   }
  ]
 },
 {
  "name": "The Long Haul",
  "gridWidth": 13,
  "gridHeight": 13,
  "obstacles": [
   {
    "x": 1,
    "y": 12,
    "type": "rock"
   },
   {
    "x": 9,
    "y": 6,
    "type": "pier"
   },
   {
    "x": 10,
    "y": 6,
    "type": "pier"
   },
   {
    "x": 0,
    "y": 9,
    "type": "pier"
   },
   {
    "x": 4,
    "y": 12,
    "type": "buoy"
   },
   {
    "x": 12,
    "y": 6,
    "type": "pier"
   },
   {
    "x": 10,
    "y": 1,
    "type": "pier"
   },
   {
    "x": 1,
    "y": 0,
    "type": "pier"
   }
  ],
  "ships": [
   {
    "x": 5,
    "y": 4,
    "direction": "E",
    "length": 2
   },
   {
    "x": 12,
    "y": 2,
    "direction": "N",
    "length": 3
   },
   {
    "x": 6,
    "y": 7,
    "direction": "N",
    "length": 3
   },
   {
    "x": 7,
    "y": 7,
    "direction": "E",
    "length": 2
   },
   {
    "x": 6,
    "y": 11,
    "direction": "E",
    "length": 3
   },
   {
    "x": 1,
    "y": 9,
    "direction": "E",
    "length": 2
   },
   {
    "x": 0,
    "y": 4,
    "direction": "N",
    "length": 3
   },
   {
    "x": 5,
    "y": 5,
    "direction": "S",
    "length": 2
   },
   {
    "x": 7,
    "y": 4,
    "direction": "S",
    "length": 3
   },
   {
    "x": 11,
    "y": 2,
    "direction": "S",
    "length": 2
   },
   {
    "x": 2,
    "y": 1,
    "direction": "N",
    "length": 2
   },
   {
    "x": 4,
    "y": 6,
    "direction": "W",
    "length": 1
   },
   {
    "x": 1,
    "y": 3,
    "direction": "W",
    "length": 3
   },
   {
    "x": 9,
    "y": 9,
    "direction": "S",
    "length": 1
   },
   {
    "x": 12,
    "y": 10,
    "direction": "E",
    "length": 1
   },
   {
    "x": 5,
    "y": 8,
    "direction": "S",
    "length": 1
   },
   {
    "x": 12,
    "y": 7,
    "direction": "S",
    "length": 1
   },
   {
    "x": 2,
    "y": 7,
    "direction": "E",
    "length": 4
   },
   {
    "x": 4,
    "y": 4,
    "direction": "N",
    "length": 2
   },
   {
    "x": 8,
    "y": 8,
    "direction": "E",
    "length": 1
   },
   {
    "x": 8,
    "y": 3,
    "direction": "S",
    "length": 4
   },
   {
    "x": 11,
    "y": 6,
    "direction": "S",
    "length": 2
   },
   {
    "x": 11,
    "y": 5,
    "direction": "E",
    "length": 1
   },
   {
    "x": 1,
    "y": 8,
    "direction": "E",
    "length": 4
   },
   {
    "x": 1,
    "y": 10,
    "direction": "E",
    "length": 1
   },
   {
    "x": 8,
    "y": 10,
    "direction": "S",
    "length": 1
   },
   {
    "x": 7,
    "y": 2,
    "direction": "E",
    "length": 3
   },
   {
    "x": 6,
    "y": 2,
    "direction": "E",
    "length": 1
   },
   {
    "x": 10,
    "y": 10,
    "direction": "E",
    "length": 2
   },
   {
    "x": 10,
    "y": 2,
    "direction": "E",
    "length": 1
   },
   {
    "x": 3,
    "y": 11,
    "direction": "E",
    "length": 1
   },
   {
    "x": 8,
    "y": 12,
    "direction": "E",
    "length": 2
   }
  ]
 },
 {
  "name": "Evening Jam",
  "gridWidth": 13,
  "gridHeight": 13,
  "obstacles": [
   {
    "x": 9,
    "y": 9,
    "type": "pier"
   },
   {
    "x": 1,
    "y": 2,
    "type": "rock"
   },
   {
    "x": 12,
    "y": 2,
    "type": "rock"
   },
   {
    "x": 4,
    "y": 9,
    "type": "pier"
   },
   {
    "x": 8,
    "y": 12,
    "type": "pier"
   },
   {
    "x": 7,
    "y": 2,
    "type": "buoy"
   },
   {
    "x": 2,
    "y": 7,
    "type": "buoy"
   },
   {
    "x": 8,
    "y": 1,
    "type": "rock"
   }
  ],
  "ships": [
   {
    "x": 12,
    "y": 6,
    "direction": "S",
    "length": 3
   },
   {
    "x": 0,
    "y": 0,
    "direction": "E",
    "length": 3
   },
   {
    "x": 9,
    "y": 6,
    "direction": "N",
    "length": 2
   },
   {
    "x": 7,
    "y": 4,
    "direction": "W",
    "length": 3
   },
   {
    "x": 6,
    "y": 10,
    "direction": "N",
    "length": 3
   },
   {
    "x": 5,
    "y": 0,
    "direction": "N",
    "length": 3
   },
   {
    "x": 6,
    "y": 0,
    "direction": "N",
    "length": 1
   },
   {
    "x": 7,
    "y": 3,
    "direction": "E",
    "length": 3
   },
   {
    "x": 12,
    "y": 9,
    "direction": "S",
    "length": 3
   },
   {
    "x": 2,
    "y": 6,
    "direction": "E",
    "length": 4
   },
   {
    "x": 9,
    "y": 12,
    "direction": "E",
    "length": 1
   },
   {
    "x": 1,
    "y": 9,
    "direction": "W",
    "length": 2
   },
   {
    "x": 5,
    "y": 12,
    "direction": "S",
    "length": 1
   },
   {
    "x": 11,
    "y": 0,
    "direction": "N",
    "length": 4
   },
   {
    "x": 4,
    "y": 8,
    "direction": "W",
    "length": 2
   },
   {
    "x": 6,
    "y": 6,
    "direction": "E",
    "length": 1
   },
   {
    "x": 4,
    "y": 3,
    "direction": "E",
    "length": 3
   },
   {
    "x": 10,
    "y": 5,
    "direction": "W",
    "length": 2
   },
   {
    "x": 10,
    "y": 10,
    "direction": "W",
    "length": 2
   },
   {
    "x": 0,
    "y": 2,
    "direction": "N",
    "length": 4
   },
   {
    "x": 6,
    "y": 9,
    "direction": "N",
    "length": 1
   },
   {
    "x": 0,
    "y": 6,
    "direction": "N",
    "length": 2
   },
   {
    "x": 5,
    "y": 5,
    "direction": "W",
    "length": 3
   },
   {
    "x": 2,
    "y": 3,
    "direction": "N",
    "length": 1
   },
   {
    "x": 4,
    "y": 10,
    "direction": "S",
    "length": 2
   },
   {
    "x": 5,
    "y": 4,
    "direction": "W",
    "length": 2
   },
   {
    "x": 10,
    "y": 4,
    "direction": "W",
    "length": 3
   },
   {
    "x": 1,
    "y": 10,
    "direction": "W",
    "length": 2
   },
   {
    "x": 6,
    "y": 1,
    "direction": "W",
    "length": 2
   },
   {
    "x": 3,
    "y": 2,
    "direction": "N",
    "length": 2
   },
   {
    "x": 10,
    "y": 6,
    "direction": "N",
    "length": 4
   },
   {
    "x": 8,
    "y": 5,
    "direction": "W",
    "length": 2
   },
   {
    "x": 9,
    "y": 11,
    "direction": "W",
    "length": 3
   },
   {
    "x": 10,
    "y": 0,
    "direction": "N",
    "length": 4
   },
   {
    "x": 2,
    "y": 11,
    "direction": "W",
    "length": 1
   }
  ]
 },
 {
  "name": "Grand Harbor",
  "gridWidth": 14,
  "gridHeight": 14,
  "obstacles": [
   {
    "x": 4,
    "y": 8,
    "type": "rock"
   },
   {
    "x": 5,
    "y": 9,
    "type": "rock"
   },
   {
    "x": 4,
    "y": 11,
    "type": "pier"
   },
   {
    "x": 7,
    "y": 11,
    "type": "rock"
   },
   {
    "x": 6,
    "y": 0,
    "type": "rock"
   },
   {
    "x": 3,
    "y": 10,
    "type": "buoy"
   },
   {
    "x": 3,
    "y": 1,
    "type": "pier"
   },
   {
    "x": 6,
    "y": 2,
    "type": "buoy"
   },
   {
    "x": 8,
    "y": 13,
    "type": "buoy"
   },
   {
    "x": 12,
    "y": 8,
    "type": "rock"
   }
  ],
  "ships": [
   {
    "x": 10,
    "y": 7,
    "direction": "E",
    "length": 2
   },
   {
    "x": 11,
    "y": 9,
    "direction": "N",
    "length": 2
   },
   {
    "x": 7,
    "y": 12,
    "direction": "E",
    "length": 4
   },
   {
    "x": 9,
    "y": 3,
    "direction": "N",
    "length": 3
   },
   {
    "x": 13,
    "y": 3,
    "direction": "N",
    "length": 3
   },
   {
    "x": 6,
    "y": 10,
    "direction": "S",
    "length": 1
   },
   {
    "x": 3,
    "y": 11,
    "direction": "S",
    "length": 3
   },
   {
    "x": 1,
    "y": 8,
    "direction": "N",
    "length": 2
   },
   {
    "x": 6,
    "y": 4,
    "direction": "W",
    "length": 2
   },
   {
    "x": 11,
    "y": 4,
    "direction": "N",
    "length": 2
   },
   {
    "x": 10,
    "y": 0,
    "direction": "S",
    "length": 2
   },
   {
    "x": 10,
    "y": 4,
    "direction": "S",
    "length": 3
   },
   {
    "x": 6,
    "y": 7,
    "direction": "S",
    "length": 2
   },
   {
    "x": 9,
    "y": 13,
    "direction": "E",
    "length": 4
   },
   {
    "x": 7,
    "y": 13,
    "direction": "S",
    "length": 1
   },
   {
    "x": 9,
    "y": 10,
    "direction": "E",
    "length": 1
   },
   {
    "x": 1,
    "y": 4,
    "direction": "W",
    "length": 1
   },
   {
    "x": 1,
    "y": 10,
    "direction": "S",
    "length": 4
   },
   {
    "x": 11,
    "y": 0,
    "direction": "E",
    "length": 3
   },
   {
    "x": 7,
    "y": 1,
    "direction": "N",
    "length": 2
   },
   {
    "x": 13,
    "y": 8,
    "direction": "E",
    "length": 1
   },
   {
    "x": 0,
    "y": 3,
    "direction": "W",
    "length": 1
   },
   {
    "x": 7,
    "y": 7,
    "direction": "W",
    "length": 1
   },
   {
    "x": 4,
    "y": 2,
    "direction": "N",
    "length": 2
   },
   {
    "x": 5,
    "y": 1,
    "direction": "N",
    "length": 3
   },
   {
    "x": 4,
    "y": 12,
    "direction": "S",
    "length": 2
   },
   {
    "x": 2,
    "y": 3,
    "direction": "S",
    "length": 4
   },
   {
    "x": 0,
    "y": 4,
    "direction": "S",
    "length": 4
   },
   {
    "x": 8,
    "y": 9,
    "direction": "N",
    "length": 3
   },
   {
    "x": 9,
    "y": 2,
    "direction": "E",
    "length": 1
   },
   {
    "x": 4,
    "y": 5,
    "direction": "W",
    "length": 4
   },
   {
    "x": 2,
    "y": 8,
    "direction": "W",
    "length": 2
   },
   {
    "x": 1,
    "y": 2,
    "direction": "W",
    "length": 3
   },
   {
    "x": 9,
    "y": 8,
    "direction": "S",
    "length": 2
   },
   {
    "x": 13,
    "y": 11,
    "direction": "S",
    "length": 2
   },
   {
    "x": 4,
    "y": 4,
    "direction": "W",
    "length": 2
   },
   {
    "x": 6,
    "y": 3,
    "direction": "S",
    "length": 1
   },
   {
    "x": 0,
    "y": 12,
    "direction": "S",
    "length": 2
   },
   {
    "x": 11,
    "y": 6,
    "direction": "N",
    "length": 1
   },
   {
    "x": 7,
    "y": 6,
    "direction": "E",
    "length": 3
   }
  ]
 },
 {
  "name": "The Strait",
  "gridWidth": 9,
  "gridHeight": 9,
  "obstacles": [],
  "ships": [
   {
    "x": 3,
    "y": 4,
    "direction": "E",
    "length": 4
   },
   {
    "x": 6,
    "y": 5,
    "direction": "N",
    "length": 2
   },
   {
    "x": 0,
    "y": 5,
    "direction": "E",
    "length": 2
   },
   {
    "x": 5,
    "y": 1,
    "direction": "W",
    "length": 4
   },
   {
    "x": 2,
    "y": 1,
    "direction": "N",
    "length": 3
   },
   {
    "x": 8,
    "y": 3,
    "direction": "N",
    "length": 3
   },
   {
    "x": 2,
    "y": 8,
    "direction": "W",
    "length": 4
   },
   {
    "x": 8,
    "y": 6,
    "direction": "S",
    "length": 2
   },
   {
    "x": 4,
    "y": 5,
    "direction": "S",
    "length": 3
   },
   {
    "x": 5,
    "y": 7,
    "direction": "W",
    "length": 2
   }
  ],
  "patrols": [
   {
    "axis": "h",
    "line": 0,
    "length": 3,
    "speed": 1.3,
    "range": [
     0,
     8
    ],
    "startPos": 4,
    "startDir": 1
   }
  ]
 },
 {
  "name": "First Watch",
  "gridWidth": 9,
  "gridHeight": 9,
  "obstacles": [
   {
    "x": 7,
    "y": 8,
    "type": "pier"
   }
  ],
  "ships": [
   {
    "x": 3,
    "y": 1,
    "direction": "S",
    "length": 2
   },
   {
    "x": 3,
    "y": 3,
    "direction": "S",
    "length": 3
   },
   {
    "x": 4,
    "y": 4,
    "direction": "E",
    "length": 2
   },
   {
    "x": 7,
    "y": 2,
    "direction": "N",
    "length": 3
   },
   {
    "x": 5,
    "y": 2,
    "direction": "W",
    "length": 1
   },
   {
    "x": 4,
    "y": 6,
    "direction": "N",
    "length": 3
   },
   {
    "x": 1,
    "y": 1,
    "direction": "S",
    "length": 1
   },
   {
    "x": 2,
    "y": 6,
    "direction": "N",
    "length": 1
   },
   {
    "x": 0,
    "y": 4,
    "direction": "E",
    "length": 1
   },
   {
    "x": 3,
    "y": 8,
    "direction": "S",
    "length": 1
   },
   {
    "x": 2,
    "y": 7,
    "direction": "E",
    "length": 2
   },
   {
    "x": 0,
    "y": 1,
    "direction": "S",
    "length": 1
   }
  ],
  "patrols": [
   {
    "axis": "h",
    "line": 0,
    "length": 3,
    "speed": 1.5,
    "range": [
     0,
     8
    ],
    "startPos": 1,
    "startDir": 1
   }
  ]
 },
 {
  "name": "Patrol Waters",
  "gridWidth": 10,
  "gridHeight": 10,
  "obstacles": [
   {
    "x": 8,
    "y": 5,
    "type": "buoy"
   }
  ],
  "ships": [
   {
    "x": 9,
    "y": 6,
    "direction": "W",
    "length": 1
   },
   {
    "x": 2,
    "y": 6,
    "direction": "W",
    "length": 1
   },
   {
    "x": 5,
    "y": 6,
    "direction": "W",
    "length": 2
   },
   {
    "x": 1,
    "y": 1,
    "direction": "S",
    "length": 3
   },
   {
    "x": 4,
    "y": 4,
    "direction": "E",
    "length": 4
   },
   {
    "x": 6,
    "y": 3,
    "direction": "E",
    "length": 3
   },
   {
    "x": 6,
    "y": 1,
    "direction": "E",
    "length": 3
   },
   {
    "x": 1,
    "y": 6,
    "direction": "S",
    "length": 2
   },
   {
    "x": 4,
    "y": 0,
    "direction": "S",
    "length": 2
   },
   {
    "x": 5,
    "y": 7,
    "direction": "S",
    "length": 2
   },
   {
    "x": 9,
    "y": 0,
    "direction": "N",
    "length": 2
   },
   {
    "x": 2,
    "y": 8,
    "direction": "E",
    "length": 1
   },
   {
    "x": 9,
    "y": 2,
    "direction": "S",
    "length": 3
   },
   {
    "x": 4,
    "y": 2,
    "direction": "S",
    "length": 2
   }
  ],
  "patrols": [
   {
    "axis": "h",
    "line": 9,
    "length": 3,
    "speed": 1.5,
    "range": [
     0,
     9
    ],
    "startPos": 5,
    "startDir": 1
   }
  ]
 },
 {
  "name": "Between Rounds",
  "gridWidth": 10,
  "gridHeight": 10,
  "obstacles": [
   {
    "x": 3,
    "y": 9,
    "type": "rock"
   },
   {
    "x": 7,
    "y": 4,
    "type": "rock"
   }
  ],
  "ships": [
   {
    "x": 0,
    "y": 6,
    "direction": "W",
    "length": 1
   },
   {
    "x": 5,
    "y": 7,
    "direction": "E",
    "length": 4
   },
   {
    "x": 1,
    "y": 4,
    "direction": "N",
    "length": 4
   },
   {
    "x": 4,
    "y": 2,
    "direction": "E",
    "length": 2
   },
   {
    "x": 9,
    "y": 6,
    "direction": "S",
    "length": 3
   },
   {
    "x": 2,
    "y": 6,
    "direction": "N",
    "length": 4
   },
   {
    "x": 8,
    "y": 1,
    "direction": "W",
    "length": 2
   },
   {
    "x": 0,
    "y": 2,
    "direction": "E",
    "length": 3
   },
   {
    "x": 6,
    "y": 3,
    "direction": "N",
    "length": 4
   },
   {
    "x": 3,
    "y": 1,
    "direction": "N",
    "length": 3
   },
   {
    "x": 6,
    "y": 2,
    "direction": "E",
    "length": 1
   },
   {
    "x": 8,
    "y": 6,
    "direction": "E",
    "length": 1
   },
   {
    "x": 5,
    "y": 3,
    "direction": "S",
    "length": 3
   },
   {
    "x": 1,
    "y": 3,
    "direction": "W",
    "length": 2
   },
   {
    "x": 8,
    "y": 2,
    "direction": "S",
    "length": 2
   }
  ],
  "patrols": [
   {
    "axis": "h",
    "line": 0,
    "length": 4,
    "speed": 1.4,
    "range": [
     0,
     9
    ],
    "startPos": 4,
    "startDir": 1
   }
  ]
 },
 {
  "name": "Quick Slip",
  "gridWidth": 10,
  "gridHeight": 10,
  "obstacles": [
   {
    "x": 7,
    "y": 3,
    "type": "buoy"
   },
   {
    "x": 3,
    "y": 7,
    "type": "rock"
   }
  ],
  "ships": [
   {
    "x": 3,
    "y": 4,
    "direction": "W",
    "length": 4
   },
   {
    "x": 2,
    "y": 9,
    "direction": "W",
    "length": 4
   },
   {
    "x": 4,
    "y": 2,
    "direction": "S",
    "length": 2
   },
   {
    "x": 6,
    "y": 8,
    "direction": "E",
    "length": 2
   },
   {
    "x": 9,
    "y": 6,
    "direction": "S",
    "length": 4
   },
   {
    "x": 9,
    "y": 2,
    "direction": "N",
    "length": 3
   },
   {
    "x": 2,
    "y": 1,
    "direction": "W",
    "length": 3
   },
   {
    "x": 0,
    "y": 5,
    "direction": "E",
    "length": 1
   },
   {
    "x": 0,
    "y": 6,
    "direction": "E",
    "length": 4
   },
   {
    "x": 8,
    "y": 5,
    "direction": "N",
    "length": 1
   },
   {
    "x": 7,
    "y": 1,
    "direction": "W",
    "length": 3
   },
   {
    "x": 0,
    "y": 7,
    "direction": "N",
    "length": 3
   },
   {
    "x": 8,
    "y": 7,
    "direction": "N",
    "length": 2
   },
   {
    "x": 7,
    "y": 4,
    "direction": "S",
    "length": 3
   },
   {
    "x": 1,
    "y": 5,
    "direction": "E",
    "length": 4
   },
   {
    "x": 2,
    "y": 3,
    "direction": "W",
    "length": 2
   }
  ],
  "patrols": [
   {
    "axis": "h",
    "line": 0,
    "length": 3,
    "speed": 1.9,
    "range": [
     0,
     9
    ],
    "startPos": 6,
    "startDir": -1
   }
  ]
 },
 {
  "name": "Two Sentries",
  "gridWidth": 11,
  "gridHeight": 11,
  "obstacles": [
   {
    "x": 1,
    "y": 2,
    "type": "pier"
   },
   {
    "x": 4,
    "y": 2,
    "type": "buoy"
   }
  ],
  "ships": [
   {
    "x": 9,
    "y": 1,
    "direction": "N",
    "length": 2
   },
   {
    "x": 7,
    "y": 7,
    "direction": "E",
    "length": 3
   },
   {
    "x": 6,
    "y": 1,
    "direction": "E",
    "length": 2
   },
   {
    "x": 8,
    "y": 8,
    "direction": "E",
    "length": 3
   },
   {
    "x": 3,
    "y": 6,
    "direction": "S",
    "length": 2
   },
   {
    "x": 4,
    "y": 7,
    "direction": "W",
    "length": 1
   },
   {
    "x": 4,
    "y": 5,
    "direction": "S",
    "length": 2
   },
   {
    "x": 10,
    "y": 1,
    "direction": "S",
    "length": 2
   },
   {
    "x": 5,
    "y": 7,
    "direction": "N",
    "length": 2
   },
   {
    "x": 1,
    "y": 8,
    "direction": "E",
    "length": 4
   },
   {
    "x": 6,
    "y": 2,
    "direction": "N",
    "length": 3
   },
   {
    "x": 4,
    "y": 4,
    "direction": "S",
    "length": 1
   },
   {
    "x": 2,
    "y": 5,
    "direction": "E",
    "length": 1
   },
   {
    "x": 0,
    "y": 7,
    "direction": "N",
    "length": 2
   },
   {
    "x": 7,
    "y": 4,
    "direction": "S",
    "length": 3
   },
   {
    "x": 0,
    "y": 3,
    "direction": "E",
    "length": 3
   },
   {
    "x": 9,
    "y": 9,
    "direction": "W",
    "length": 1
   },
   {
    "x": 2,
    "y": 9,
    "direction": "N",
    "length": 1
   }
  ],
  "patrols": [
   {
    "axis": "h",
    "line": 0,
    "length": 3,
    "speed": 1.5,
    "range": [
     0,
     10
    ],
    "startPos": 1,
    "startDir": 1
   },
   {
    "axis": "h",
    "line": 10,
    "length": 3,
    "speed": 1.7,
    "range": [
     0,
     10
    ],
    "startPos": 7,
    "startDir": 1
   }
  ]
 },
 {
  "name": "Changing of the Guard",
  "gridWidth": 11,
  "gridHeight": 11,
  "obstacles": [
   {
    "x": 9,
    "y": 1,
    "type": "rock"
   },
   {
    "x": 6,
    "y": 2,
    "type": "rock"
   },
   {
    "x": 3,
    "y": 8,
    "type": "rock"
   }
  ],
  "ships": [
   {
    "x": 7,
    "y": 1,
    "direction": "W",
    "length": 2
   },
   {
    "x": 7,
    "y": 6,
    "direction": "S",
    "length": 3
   },
   {
    "x": 5,
    "y": 9,
    "direction": "W",
    "length": 1
   },
   {
    "x": 2,
    "y": 5,
    "direction": "E",
    "length": 2
   },
   {
    "x": 6,
    "y": 1,
    "direction": "N",
    "length": 1
   },
   {
    "x": 1,
    "y": 6,
    "direction": "S",
    "length": 2
   },
   {
    "x": 5,
    "y": 4,
    "direction": "W",
    "length": 3
   },
   {
    "x": 8,
    "y": 9,
    "direction": "W",
    "length": 3
   },
   {
    "x": 8,
    "y": 3,
    "direction": "S",
    "length": 3
   },
   {
    "x": 1,
    "y": 2,
    "direction": "N",
    "length": 2
   },
   {
    "x": 6,
    "y": 9,
    "direction": "W",
    "length": 2
   },
   {
    "x": 2,
    "y": 9,
    "direction": "W",
    "length": 3
   },
   {
    "x": 9,
    "y": 4,
    "direction": "S",
    "length": 1
   },
   {
    "x": 6,
    "y": 6,
    "direction": "E",
    "length": 1
   },
   {
    "x": 4,
    "y": 6,
    "direction": "S",
    "length": 3
   },
   {
    "x": 2,
    "y": 3,
    "direction": "S",
    "length": 2
   },
   {
    "x": 8,
    "y": 6,
    "direction": "S",
    "length": 1
   },
   {
    "x": 0,
    "y": 8,
    "direction": "S",
    "length": 2
   },
   {
    "x": 6,
    "y": 7,
    "direction": "S",
    "length": 2
   }
  ],
  "patrols": [
   {
    "axis": "h",
    "line": 0,
    "length": 3,
    "speed": 1.6,
    "range": [
     0,
     10
    ],
    "startPos": 1,
    "startDir": 1
   },
   {
    "axis": "h",
    "line": 10,
    "length": 3,
    "speed": 1.4,
    "range": [
     0,
     10
    ],
    "startPos": 7,
    "startDir": 1
   }
  ]
 },
 {
  "name": "Under Escort",
  "gridWidth": 11,
  "gridHeight": 11,
  "obstacles": [
   {
    "x": 8,
    "y": 5,
    "type": "buoy"
   },
   {
    "x": 10,
    "y": 1,
    "type": "pier"
   },
   {
    "x": 9,
    "y": 4,
    "type": "pier"
   }
  ],
  "ships": [
   {
    "x": 6,
    "y": 3,
    "direction": "E",
    "length": 2
   },
   {
    "x": 8,
    "y": 9,
    "direction": "E",
    "length": 2
   },
   {
    "x": 9,
    "y": 3,
    "direction": "N",
    "length": 1
   },
   {
    "x": 4,
    "y": 2,
    "direction": "W",
    "length": 3
   },
   {
    "x": 9,
    "y": 6,
    "direction": "W",
    "length": 2
   },
   {
    "x": 10,
    "y": 9,
    "direction": "E",
    "length": 1
   },
   {
    "x": 0,
    "y": 8,
    "direction": "S",
    "length": 1
   },
   {
    "x": 6,
    "y": 4,
    "direction": "S",
    "length": 2
   },
   {
    "x": 5,
    "y": 5,
    "direction": "N",
    "length": 4
   },
   {
    "x": 1,
    "y": 2,
    "direction": "N",
    "length": 3
   },
   {
    "x": 10,
    "y": 2,
    "direction": "S",
    "length": 4
   },
   {
    "x": 1,
    "y": 1,
    "direction": "W",
    "length": 2
   },
   {
    "x": 2,
    "y": 5,
    "direction": "N",
    "length": 4
   },
   {
    "x": 2,
    "y": 4,
    "direction": "W",
    "length": 4
   },
   {
    "x": 1,
    "y": 6,
    "direction": "S",
    "length": 1
   },
   {
    "x": 4,
    "y": 3,
    "direction": "E",
    "length": 1
   },
   {
    "x": 1,
    "y": 9,
    "direction": "W",
    "length": 4
   },
   {
    "x": 4,
    "y": 7,
    "direction": "S",
    "length": 1
   },
   {
    "x": 6,
    "y": 8,
    "direction": "E",
    "length": 1
   },
   {
    "x": 7,
    "y": 2,
    "direction": "E",
    "length": 3
   }
  ],
  "patrols": [
   {
    "axis": "h",
    "line": 0,
    "length": 4,
    "speed": 1.6,
    "range": [
     0,
     10
    ],
    "startPos": 7,
    "startDir": 1
   },
   {
    "axis": "h",
    "line": 10,
    "length": 3,
    "speed": 1.9,
    "range": [
     0,
     10
    ],
    "startPos": 0,
    "startDir": -1
   }
  ]
 },
 {
  "name": "Measured Steps",
  "gridWidth": 12,
  "gridHeight": 12,
  "obstacles": [
   {
    "x": 2,
    "y": 5,
    "type": "pier"
   },
   {
    "x": 7,
    "y": 6,
    "type": "pier"
   },
   {
    "x": 11,
    "y": 5,
    "type": "pier"
   },
   {
    "x": 5,
    "y": 8,
    "type": "rock"
   }
  ],
  "ships": [
   {
    "x": 8,
    "y": 8,
    "direction": "E",
    "length": 2
   },
   {
    "x": 3,
    "y": 3,
    "direction": "N",
    "length": 1
   },
   {
    "x": 0,
    "y": 2,
    "direction": "E",
    "length": 4
   },
   {
    "x": 0,
    "y": 3,
    "direction": "W",
    "length": 1
   },
   {
    "x": 10,
    "y": 8,
    "direction": "N",
    "length": 3
   },
   {
    "x": 6,
    "y": 5,
    "direction": "N",
    "length": 3
   },
   {
    "x": 6,
    "y": 9,
    "direction": "W",
    "length": 3
   },
   {
    "x": 8,
    "y": 3,
    "direction": "W",
    "length": 4
   },
   {
    "x": 3,
    "y": 9,
    "direction": "W",
    "length": 1
   },
   {
    "x": 8,
    "y": 4,
    "direction": "E",
    "length": 2
   },
   {
    "x": 8,
    "y": 10,
    "direction": "E",
    "length": 2
   },
   {
    "x": 4,
    "y": 4,
    "direction": "E",
    "length": 3
   },
   {
    "x": 7,
    "y": 7,
    "direction": "W",
    "length": 1
   },
   {
    "x": 4,
    "y": 2,
    "direction": "N",
    "length": 2
   },
   {
    "x": 5,
    "y": 1,
    "direction": "W",
    "length": 3
   },
   {
    "x": 2,
    "y": 8,
    "direction": "S",
    "length": 2
   },
   {
    "x": 1,
    "y": 4,
    "direction": "E",
    "length": 3
   },
   {
    "x": 8,
    "y": 7,
    "direction": "W",
    "length": 3
   },
   {
    "x": 4,
    "y": 9,
    "direction": "N",
    "length": 2
   },
   {
    "x": 9,
    "y": 1,
    "direction": "N",
    "length": 1
   },
   {
    "x": 3,
    "y": 7,
    "direction": "W",
    "length": 3
   },
   {
    "x": 0,
    "y": 10,
    "direction": "E",
    "length": 4
   }
  ],
  "patrols": [
   {
    "axis": "h",
    "line": 0,
    "length": 3,
    "speed": 1.7,
    "range": [
     0,
     11
    ],
    "startPos": 7,
    "startDir": -1
   },
   {
    "axis": "h",
    "line": 11,
    "length": 4,
    "speed": 1.5,
    "range": [
     0,
     11
    ],
    "startPos": 1,
    "startDir": -1
   }
  ]
 },
 {
  "name": "Double Watch",
  "gridWidth": 12,
  "gridHeight": 12,
  "obstacles": [
   {
    "x": 4,
    "y": 4,
    "type": "pier"
   },
   {
    "x": 6,
    "y": 6,
    "type": "pier"
   },
   {
    "x": 4,
    "y": 9,
    "type": "rock"
   },
   {
    "x": 7,
    "y": 9,
    "type": "rock"
   }
  ],
  "ships": [
   {
    "x": 6,
    "y": 3,
    "direction": "W",
    "length": 4
   },
   {
    "x": 8,
    "y": 1,
    "direction": "S",
    "length": 2
   },
   {
    "x": 2,
    "y": 8,
    "direction": "W",
    "length": 2
   },
   {
    "x": 11,
    "y": 1,
    "direction": "S",
    "length": 3
   },
   {
    "x": 3,
    "y": 10,
    "direction": "E",
    "length": 1
   },
   {
    "x": 6,
    "y": 5,
    "direction": "E",
    "length": 2
   },
   {
    "x": 5,
    "y": 3,
    "direction": "S",
    "length": 2
   },
   {
    "x": 2,
    "y": 4,
    "direction": "S",
    "length": 4
   },
   {
    "x": 1,
    "y": 9,
    "direction": "W",
    "length": 2
   },
   {
    "x": 10,
    "y": 2,
    "direction": "N",
    "length": 3
   },
   {
    "x": 1,
    "y": 3,
    "direction": "N",
    "length": 2
   },
   {
    "x": 4,
    "y": 10,
    "direction": "E",
    "length": 2
   },
   {
    "x": 8,
    "y": 10,
    "direction": "S",
    "length": 1
   },
   {
    "x": 2,
    "y": 2,
    "direction": "W",
    "length": 2
   },
   {
    "x": 1,
    "y": 1,
    "direction": "N",
    "length": 2
   },
   {
    "x": 6,
    "y": 7,
    "direction": "W",
    "length": 4
   },
   {
    "x": 5,
    "y": 6,
    "direction": "S",
    "length": 1
   },
   {
    "x": 9,
    "y": 4,
    "direction": "N",
    "length": 3
   },
   {
    "x": 4,
    "y": 2,
    "direction": "W",
    "length": 3
   },
   {
    "x": 0,
    "y": 7,
    "direction": "S",
    "length": 3
   },
   {
    "x": 6,
    "y": 8,
    "direction": "W",
    "length": 2
   },
   {
    "x": 10,
    "y": 1,
    "direction": "W",
    "length": 1
   },
   {
    "x": 10,
    "y": 7,
    "direction": "W",
    "length": 2
   },
   {
    "x": 0,
    "y": 10,
    "direction": "E",
    "length": 3
   }
  ],
  "patrols": [
   {
    "axis": "h",
    "line": 0,
    "length": 4,
    "speed": 1.9,
    "range": [
     0,
     11
    ],
    "startPos": 8,
    "startDir": 1
   },
   {
    "axis": "h",
    "line": 11,
    "length": 3,
    "speed": 2.1,
    "range": [
     0,
     11
    ],
    "startPos": 1,
    "startDir": 1
   }
  ]
 },
 {
  "name": "Flanked",
  "gridWidth": 12,
  "gridHeight": 12,
  "obstacles": [
   {
    "x": 5,
    "y": 7,
    "type": "pier"
   },
   {
    "x": 5,
    "y": 10,
    "type": "rock"
   },
   {
    "x": 9,
    "y": 2,
    "type": "pier"
   }
  ],
  "ships": [
   {
    "x": 8,
    "y": 9,
    "direction": "S",
    "length": 1
   },
   {
    "x": 6,
    "y": 6,
    "direction": "E",
    "length": 4
   },
   {
    "x": 7,
    "y": 11,
    "direction": "E",
    "length": 3
   },
   {
    "x": 9,
    "y": 7,
    "direction": "S",
    "length": 3
   },
   {
    "x": 7,
    "y": 1,
    "direction": "E",
    "length": 4
   },
   {
    "x": 6,
    "y": 10,
    "direction": "E",
    "length": 3
   },
   {
    "x": 3,
    "y": 1,
    "direction": "E",
    "length": 3
   },
   {
    "x": 6,
    "y": 5,
    "direction": "E",
    "length": 4
   },
   {
    "x": 3,
    "y": 5,
    "direction": "S",
    "length": 3
   },
   {
    "x": 0,
    "y": 3,
    "direction": "N",
    "length": 3
   },
   {
    "x": 1,
    "y": 4,
    "direction": "N",
    "length": 4
   },
   {
    "x": 4,
    "y": 7,
    "direction": "N",
    "length": 3
   },
   {
    "x": 3,
    "y": 3,
    "direction": "E",
    "length": 2
   },
   {
    "x": 1,
    "y": 8,
    "direction": "W",
    "length": 1
   },
   {
    "x": 8,
    "y": 2,
    "direction": "S",
    "length": 2
   },
   {
    "x": 3,
    "y": 4,
    "direction": "E",
    "length": 3
   },
   {
    "x": 0,
    "y": 8,
    "direction": "N",
    "length": 1
   },
   {
    "x": 4,
    "y": 11,
    "direction": "E",
    "length": 2
   },
   {
    "x": 10,
    "y": 5,
    "direction": "N",
    "length": 3
   },
   {
    "x": 2,
    "y": 6,
    "direction": "S",
    "length": 1
   },
   {
    "x": 6,
    "y": 3,
    "direction": "E",
    "length": 2
   },
   {
    "x": 0,
    "y": 10,
    "direction": "W",
    "length": 2
   },
   {
    "x": 6,
    "y": 7,
    "direction": "N",
    "length": 3
   },
   {
    "x": 10,
    "y": 10,
    "direction": "N",
    "length": 1
   }
  ],
  "patrols": [
   {
    "axis": "h",
    "line": 0,
    "length": 3,
    "speed": 1.6,
    "range": [
     0,
     9
    ],
    "startPos": 5,
    "startDir": 1
   },
   {
    "axis": "v",
    "line": 11,
    "length": 3,
    "speed": 1.8,
    "range": [
     2,
     11
    ],
    "startPos": 7,
    "startDir": -1
   }
  ]
 },
 {
  "name": "Coast Runner",
  "gridWidth": 12,
  "gridHeight": 12,
  "obstacles": [
   {
    "x": 2,
    "y": 3,
    "type": "pier"
   },
   {
    "x": 4,
    "y": 6,
    "type": "pier"
   },
   {
    "x": 11,
    "y": 1,
    "type": "pier"
   },
   {
    "x": 3,
    "y": 5,
    "type": "pier"
   }
  ],
  "ships": [
   {
    "x": 7,
    "y": 7,
    "direction": "E",
    "length": 1
   },
   {
    "x": 8,
    "y": 5,
    "direction": "N",
    "length": 1
   },
   {
    "x": 8,
    "y": 4,
    "direction": "W",
    "length": 2
   },
   {
    "x": 1,
    "y": 3,
    "direction": "N",
    "length": 2
   },
   {
    "x": 4,
    "y": 10,
    "direction": "E",
    "length": 4
   },
   {
    "x": 5,
    "y": 7,
    "direction": "E",
    "length": 2
   },
   {
    "x": 6,
    "y": 8,
    "direction": "S",
    "length": 2
   },
   {
    "x": 1,
    "y": 5,
    "direction": "W",
    "length": 1
   },
   {
    "x": 9,
    "y": 7,
    "direction": "E",
    "length": 2
   },
   {
    "x": 10,
    "y": 8,
    "direction": "S",
    "length": 1
   },
   {
    "x": 1,
    "y": 0,
    "direction": "W",
    "length": 3
   },
   {
    "x": 7,
    "y": 2,
    "direction": "E",
    "length": 2
   },
   {
    "x": 5,
    "y": 0,
    "direction": "W",
    "length": 2
   },
   {
    "x": 8,
    "y": 9,
    "direction": "W",
    "length": 4
   },
   {
    "x": 11,
    "y": 5,
    "direction": "S",
    "length": 4
   },
   {
    "x": 5,
    "y": 3,
    "direction": "E",
    "length": 4
   },
   {
    "x": 2,
    "y": 6,
    "direction": "S",
    "length": 4
   },
   {
    "x": 7,
    "y": 0,
    "direction": "W",
    "length": 3
   },
   {
    "x": 7,
    "y": 6,
    "direction": "E",
    "length": 2
   },
   {
    "x": 5,
    "y": 8,
    "direction": "S",
    "length": 1
   },
   {
    "x": 1,
    "y": 1,
    "direction": "W",
    "length": 3
   },
   {
    "x": 7,
    "y": 9,
    "direction": "W",
    "length": 1
   },
   {
    "x": 9,
    "y": 1,
    "direction": "N",
    "length": 3
   },
   {
    "x": 6,
    "y": 4,
    "direction": "S",
    "length": 3
   },
   {
    "x": 2,
    "y": 4,
    "direction": "W",
    "length": 2
   }
  ],
  "patrols": [
   {
    "axis": "h",
    "line": 11,
    "length": 4,
    "speed": 1.7,
    "range": [
     2,
     11
    ],
    "startPos": 5,
    "startDir": -1
   },
   {
    "axis": "v",
    "line": 0,
    "length": 3,
    "speed": 1.5,
    "range": [
     0,
     9
    ],
    "startPos": 1,
    "startDir": -1
   }
  ]
 },
 {
  "name": "Three Watchers",
  "gridWidth": 12,
  "gridHeight": 12,
  "obstacles": [
   {
    "x": 9,
    "y": 7,
    "type": "rock"
   },
   {
    "x": 4,
    "y": 9,
    "type": "pier"
   },
   {
    "x": 6,
    "y": 5,
    "type": "buoy"
   },
   {
    "x": 8,
    "y": 2,
    "type": "rock"
   }
  ],
  "ships": [
   {
    "x": 8,
    "y": 8,
    "direction": "S",
    "length": 2
   },
   {
    "x": 10,
    "y": 7,
    "direction": "S",
    "length": 3
   },
   {
    "x": 0,
    "y": 1,
    "direction": "N",
    "length": 3
   },
   {
    "x": 4,
    "y": 3,
    "direction": "N",
    "length": 4
   },
   {
    "x": 3,
    "y": 4,
    "direction": "S",
    "length": 3
   },
   {
    "x": 7,
    "y": 10,
    "direction": "N",
    "length": 1
   },
   {
    "x": 1,
    "y": 2,
    "direction": "W",
    "length": 2
   },
   {
    "x": 2,
    "y": 8,
    "direction": "E",
    "length": 4
   },
   {
    "x": 0,
    "y": 10,
    "direction": "E",
    "length": 2
   },
   {
    "x": 5,
    "y": 10,
    "direction": "E",
    "length": 2
   },
   {
    "x": 10,
    "y": 3,
    "direction": "N",
    "length": 3
   },
   {
    "x": 8,
    "y": 10,
    "direction": "E",
    "length": 3
   },
   {
    "x": 3,
    "y": 9,
    "direction": "W",
    "length": 1
   },
   {
    "x": 8,
    "y": 5,
    "direction": "S",
    "length": 2
   },
   {
    "x": 1,
    "y": 1,
    "direction": "W",
    "length": 1
   },
   {
    "x": 3,
    "y": 1,
    "direction": "W",
    "length": 1
   },
   {
    "x": 6,
    "y": 8,
    "direction": "E",
    "length": 1
   },
   {
    "x": 1,
    "y": 3,
    "direction": "N",
    "length": 4
   },
   {
    "x": 7,
    "y": 6,
    "direction": "N",
    "length": 2
   },
   {
    "x": 3,
    "y": 7,
    "direction": "S",
    "length": 1
   },
   {
    "x": 6,
    "y": 1,
    "direction": "W",
    "length": 4
   },
   {
    "x": 0,
    "y": 6,
    "direction": "S",
    "length": 2
   },
   {
    "x": 5,
    "y": 2,
    "direction": "N",
    "length": 1
   },
   {
    "x": 7,
    "y": 4,
    "direction": "N",
    "length": 2
   },
   {
    "x": 5,
    "y": 4,
    "direction": "E",
    "length": 2
   },
   {
    "x": 2,
    "y": 5,
    "direction": "N",
    "length": 2
   }
  ],
  "patrols": [
   {
    "axis": "h",
    "line": 0,
    "length": 3,
    "speed": 1.6,
    "range": [
     0,
     9
    ],
    "startPos": 1,
    "startDir": -1
   },
   {
    "axis": "h",
    "line": 11,
    "length": 3,
    "speed": 1.8,
    "range": [
     0,
     9
    ],
    "startPos": 1,
    "startDir": 1
   },
   {
    "axis": "v",
    "line": 11,
    "length": 3,
    "speed": 1.5,
    "range": [
     2,
     9
    ],
    "startPos": 3,
    "startDir": 1
   }
  ]
 },
 {
  "name": "The Cordon",
  "gridWidth": 13,
  "gridHeight": 13,
  "obstacles": [
   {
    "x": 6,
    "y": 10,
    "type": "rock"
   },
   {
    "x": 11,
    "y": 11,
    "type": "buoy"
   },
   {
    "x": 1,
    "y": 9,
    "type": "rock"
   },
   {
    "x": 6,
    "y": 4,
    "type": "pier"
   },
   {
    "x": 4,
    "y": 5,
    "type": "pier"
   }
  ],
  "ships": [
   {
    "x": 10,
    "y": 10,
    "direction": "E",
    "length": 3
   },
   {
    "x": 11,
    "y": 5,
    "direction": "E",
    "length": 2
   },
   {
    "x": 8,
    "y": 9,
    "direction": "E",
    "length": 2
   },
   {
    "x": 4,
    "y": 1,
    "direction": "W",
    "length": 2
   },
   {
    "x": 7,
    "y": 7,
    "direction": "N",
    "length": 3
   },
   {
    "x": 1,
    "y": 4,
    "direction": "W",
    "length": 3
   },
   {
    "x": 5,
    "y": 6,
    "direction": "W",
    "length": 2
   },
   {
    "x": 11,
    "y": 4,
    "direction": "N",
    "length": 1
   },
   {
    "x": 10,
    "y": 1,
    "direction": "S",
    "length": 4
   },
   {
    "x": 2,
    "y": 11,
    "direction": "W",
    "length": 1
   },
   {
    "x": 9,
    "y": 5,
    "direction": "E",
    "length": 1
   },
   {
    "x": 5,
    "y": 3,
    "direction": "E",
    "length": 3
   },
   {
    "x": 3,
    "y": 6,
    "direction": "W",
    "length": 2
   },
   {
    "x": 3,
    "y": 1,
    "direction": "S",
    "length": 2
   },
   {
    "x": 8,
    "y": 4,
    "direction": "N",
    "length": 3
   },
   {
    "x": 12,
    "y": 1,
    "direction": "N",
    "length": 3
   },
   {
    "x": 2,
    "y": 7,
    "direction": "E",
    "length": 1
   },
   {
    "x": 8,
    "y": 2,
    "direction": "E",
    "length": 2
   },
   {
    "x": 9,
    "y": 3,
    "direction": "E",
    "length": 1
   },
   {
    "x": 6,
    "y": 1,
    "direction": "W",
    "length": 3
   },
   {
    "x": 4,
    "y": 11,
    "direction": "W",
    "length": 4
   },
   {
    "x": 10,
    "y": 5,
    "direction": "S",
    "length": 1
   },
   {
    "x": 8,
    "y": 7,
    "direction": "N",
    "length": 2
   },
   {
    "x": 1,
    "y": 5,
    "direction": "N",
    "length": 3
   },
   {
    "x": 10,
    "y": 6,
    "direction": "S",
    "length": 2
   },
   {
    "x": 7,
    "y": 5,
    "direction": "N",
    "length": 2
   },
   {
    "x": 9,
    "y": 7,
    "direction": "N",
    "length": 2
   },
   {
    "x": 1,
    "y": 3,
    "direction": "E",
    "length": 4
   }
  ],
  "patrols": [
   {
    "axis": "h",
    "line": 0,
    "length": 4,
    "speed": 1.7,
    "range": [
     2,
     12
    ],
    "startPos": 3,
    "startDir": -1
   },
   {
    "axis": "h",
    "line": 12,
    "length": 3,
    "speed": 1.5,
    "range": [
     2,
     12
    ],
    "startPos": 4,
    "startDir": 1
   },
   {
    "axis": "v",
    "line": 0,
    "length": 3,
    "speed": 1.9,
    "range": [
     2,
     10
    ],
    "startPos": 2,
    "startDir": 1
   }
  ]
 },
 {
  "name": "Ring of Steel",
  "gridWidth": 13,
  "gridHeight": 13,
  "obstacles": [
   {
    "x": 6,
    "y": 8,
    "type": "rock"
   },
   {
    "x": 8,
    "y": 11,
    "type": "rock"
   },
   {
    "x": 1,
    "y": 9,
    "type": "pier"
   },
   {
    "x": 4,
    "y": 7,
    "type": "buoy"
   },
   {
    "x": 10,
    "y": 5,
    "type": "buoy"
   }
  ],
  "ships": [
   {
    "x": 1,
    "y": 5,
    "direction": "N",
    "length": 2
   },
   {
    "x": 7,
    "y": 5,
    "direction": "S",
    "length": 1
   },
   {
    "x": 10,
    "y": 10,
    "direction": "W",
    "length": 2
   },
   {
    "x": 6,
    "y": 6,
    "direction": "N",
    "length": 1
   },
   {
    "x": 2,
    "y": 6,
    "direction": "W",
    "length": 3
   },
   {
    "x": 3,
    "y": 8,
    "direction": "N",
    "length": 4
   },
   {
    "x": 8,
    "y": 10,
    "direction": "W",
    "length": 2
   },
   {
    "x": 5,
    "y": 10,
    "direction": "S",
    "length": 2
   },
   {
    "x": 2,
    "y": 2,
    "direction": "N",
    "length": 1
   },
   {
    "x": 5,
    "y": 6,
    "direction": "W",
    "length": 1
   },
   {
    "x": 7,
    "y": 3,
    "direction": "S",
    "length": 2
   },
   {
    "x": 10,
    "y": 8,
    "direction": "S",
    "length": 1
   },
   {
    "x": 11,
    "y": 1,
    "direction": "N",
    "length": 3
   },
   {
    "x": 7,
    "y": 2,
    "direction": "E",
    "length": 2
   },
   {
    "x": 5,
    "y": 2,
    "direction": "W",
    "length": 2
   },
   {
    "x": 7,
    "y": 8,
    "direction": "E",
    "length": 1
   },
   {
    "x": 3,
    "y": 4,
    "direction": "W",
    "length": 3
   },
   {
    "x": 2,
    "y": 7,
    "direction": "N",
    "length": 3
   },
   {
    "x": 11,
    "y": 5,
    "direction": "N",
    "length": 2
   },
   {
    "x": 9,
    "y": 4,
    "direction": "W",
    "length": 1
   },
   {
    "x": 10,
    "y": 9,
    "direction": "E",
    "length": 2
   },
   {
    "x": 2,
    "y": 1,
    "direction": "N",
    "length": 1
   },
   {
    "x": 3,
    "y": 1,
    "direction": "E",
    "length": 3
   },
   {
    "x": 9,
    "y": 6,
    "direction": "N",
    "length": 2
   },
   {
    "x": 8,
    "y": 6,
    "direction": "N",
    "length": 3
   },
   {
    "x": 7,
    "y": 1,
    "direction": "E",
    "length": 4
   },
   {
    "x": 1,
    "y": 2,
    "direction": "N",
    "length": 2
   },
   {
    "x": 5,
    "y": 5,
    "direction": "S",
    "length": 1
   }
  ],
  "patrols": [
   {
    "axis": "h",
    "line": 0,
    "length": 3,
    "speed": 1.4,
    "range": [
     2,
     10
    ],
    "startPos": 8,
    "startDir": -1
   },
   {
    "axis": "h",
    "line": 12,
    "length": 3,
    "speed": 1.5,
    "range": [
     2,
     10
    ],
    "startPos": 7,
    "startDir": -1
   },
   {
    "axis": "v",
    "line": 12,
    "length": 3,
    "speed": 1.3,
    "range": [
     2,
     10
    ],
    "startPos": 6,
    "startDir": -1
   },
   {
    "axis": "v",
    "line": 0,
    "length": 3,
    "speed": 1.6,
    "range": [
     2,
     10
    ],
    "startPos": 6,
    "startDir": -1
   }
  ]
 },
 {
  "name": "Four Corners",
  "gridWidth": 13,
  "gridHeight": 13,
  "obstacles": [
   {
    "x": 2,
    "y": 3,
    "type": "rock"
   },
   {
    "x": 7,
    "y": 5,
    "type": "rock"
   },
   {
    "x": 9,
    "y": 5,
    "type": "rock"
   },
   {
    "x": 5,
    "y": 7,
    "type": "rock"
   },
   {
    "x": 1,
    "y": 6,
    "type": "pier"
   },
   {
    "x": 3,
    "y": 7,
    "type": "rock"
   }
  ],
  "ships": [
   {
    "x": 8,
    "y": 8,
    "direction": "N",
    "length": 2
   },
   {
    "x": 3,
    "y": 11,
    "direction": "E",
    "length": 4
   },
   {
    "x": 5,
    "y": 10,
    "direction": "W",
    "length": 3
   },
   {
    "x": 8,
    "y": 10,
    "direction": "N",
    "length": 2
   },
   {
    "x": 2,
    "y": 8,
    "direction": "S",
    "length": 3
   },
   {
    "x": 3,
    "y": 1,
    "direction": "E",
    "length": 4
   },
   {
    "x": 3,
    "y": 4,
    "direction": "W",
    "length": 4
   },
   {
    "x": 10,
    "y": 9,
    "direction": "E",
    "length": 2
   },
   {
    "x": 5,
    "y": 2,
    "direction": "E",
    "length": 4
   },
   {
    "x": 1,
    "y": 1,
    "direction": "W",
    "length": 1
   },
   {
    "x": 6,
    "y": 7,
    "direction": "S",
    "length": 3
   },
   {
    "x": 9,
    "y": 10,
    "direction": "W",
    "length": 3
   },
   {
    "x": 1,
    "y": 3,
    "direction": "N",
    "length": 3
   },
   {
    "x": 1,
    "y": 2,
    "direction": "E",
    "length": 4
   },
   {
    "x": 9,
    "y": 11,
    "direction": "E",
    "length": 2
   },
   {
    "x": 11,
    "y": 5,
    "direction": "N",
    "length": 3
   },
   {
    "x": 6,
    "y": 5,
    "direction": "N",
    "length": 1
   },
   {
    "x": 11,
    "y": 1,
    "direction": "N",
    "length": 2
   },
   {
    "x": 7,
    "y": 1,
    "direction": "E",
    "length": 3
   },
   {
    "x": 7,
    "y": 3,
    "direction": "E",
    "length": 2
   },
   {
    "x": 7,
    "y": 7,
    "direction": "S",
    "length": 2
   },
   {
    "x": 8,
    "y": 4,
    "direction": "W",
    "length": 1
   },
   {
    "x": 2,
    "y": 5,
    "direction": "W",
    "length": 1
   },
   {
    "x": 10,
    "y": 2,
    "direction": "N",
    "length": 2
   },
   {
    "x": 2,
    "y": 11,
    "direction": "E",
    "length": 1
   },
   {
    "x": 10,
    "y": 8,
    "direction": "E",
    "length": 1
   },
   {
    "x": 4,
    "y": 6,
    "direction": "S",
    "length": 2
   },
   {
    "x": 3,
    "y": 5,
    "direction": "W",
    "length": 1
   },
   {
    "x": 7,
    "y": 6,
    "direction": "E",
    "length": 2
   },
   {
    "x": 9,
    "y": 4,
    "direction": "W",
    "length": 1
   }
  ],
  "patrols": [
   {
    "axis": "h",
    "line": 0,
    "length": 3,
    "speed": 1.7,
    "range": [
     2,
     10
    ],
    "startPos": 5,
    "startDir": -1
   },
   {
    "axis": "h",
    "line": 12,
    "length": 4,
    "speed": 1.5,
    "range": [
     2,
     10
    ],
    "startPos": 5,
    "startDir": 1
   },
   {
    "axis": "v",
    "line": 12,
    "length": 3,
    "speed": 1.8,
    "range": [
     2,
     10
    ],
    "startPos": 3,
    "startDir": 1
   },
   {
    "axis": "v",
    "line": 0,
    "length": 3,
    "speed": 1.4,
    "range": [
     2,
     10
    ],
    "startPos": 2,
    "startDir": 1
   }
  ]
 },
 {
  "name": "No Hurry",
  "gridWidth": 13,
  "gridHeight": 13,
  "obstacles": [
   {
    "x": 2,
    "y": 3,
    "type": "pier"
   },
   {
    "x": 6,
    "y": 6,
    "type": "rock"
   },
   {
    "x": 2,
    "y": 6,
    "type": "rock"
   },
   {
    "x": 7,
    "y": 9,
    "type": "pier"
   },
   {
    "x": 4,
    "y": 10,
    "type": "pier"
   },
   {
    "x": 9,
    "y": 9,
    "type": "buoy"
   }
  ],
  "ships": [
   {
    "x": 8,
    "y": 2,
    "direction": "S",
    "length": 2
   },
   {
    "x": 1,
    "y": 9,
    "direction": "W",
    "length": 2
   },
   {
    "x": 7,
    "y": 6,
    "direction": "E",
    "length": 2
   },
   {
    "x": 2,
    "y": 5,
    "direction": "E",
    "length": 3
   },
   {
    "x": 5,
    "y": 1,
    "direction": "W",
    "length": 1
   },
   {
    "x": 7,
    "y": 11,
    "direction": "E",
    "length": 1
   },
   {
    "x": 10,
    "y": 7,
    "direction": "E",
    "length": 2
   },
   {
    "x": 1,
    "y": 3,
    "direction": "W",
    "length": 1
   },
   {
    "x": 5,
    "y": 7,
    "direction": "N",
    "length": 1
   },
   {
    "x": 7,
    "y": 1,
    "direction": "E",
    "length": 3
   },
   {
    "x": 1,
    "y": 2,
    "direction": "E",
    "length": 1
   },
   {
    "x": 3,
    "y": 8,
    "direction": "E",
    "length": 4
   },
   {
    "x": 11,
    "y": 2,
    "direction": "N",
    "length": 3
   },
   {
    "x": 10,
    "y": 3,
    "direction": "N",
    "length": 4
   },
   {
    "x": 1,
    "y": 7,
    "direction": "W",
    "length": 3
   },
   {
    "x": 7,
    "y": 4,
    "direction": "N",
    "length": 2
   },
   {
    "x": 9,
    "y": 8,
    "direction": "E",
    "length": 2
   },
   {
    "x": 10,
    "y": 10,
    "direction": "E",
    "length": 2
   },
   {
    "x": 5,
    "y": 9,
    "direction": "S",
    "length": 3
   },
   {
    "x": 7,
    "y": 2,
    "direction": "E",
    "length": 1
   },
   {
    "x": 6,
    "y": 4,
    "direction": "E",
    "length": 1
   },
   {
    "x": 9,
    "y": 11,
    "direction": "S",
    "length": 1
   },
   {
    "x": 3,
    "y": 2,
    "direction": "S",
    "length": 1
   },
   {
    "x": 3,
    "y": 1,
    "direction": "N",
    "length": 1
   },
   {
    "x": 2,
    "y": 11,
    "direction": "W",
    "length": 1
   },
   {
    "x": 5,
    "y": 4,
    "direction": "N",
    "length": 3
   },
   {
    "x": 2,
    "y": 4,
    "direction": "W",
    "length": 3
   },
   {
    "x": 9,
    "y": 4,
    "direction": "E",
    "length": 1
   },
   {
    "x": 6,
    "y": 9,
    "direction": "S",
    "length": 2
   },
   {
    "x": 5,
    "y": 2,
    "direction": "N",
    "length": 1
   },
   {
    "x": 3,
    "y": 11,
    "direction": "W",
    "length": 1
   },
   {
    "x": 8,
    "y": 7,
    "direction": "W",
    "length": 1
   }
  ],
  "patrols": [
   {
    "axis": "h",
    "line": 0,
    "length": 4,
    "speed": 1.9,
    "range": [
     2,
     10
    ],
    "startPos": 4,
    "startDir": 1
   },
   {
    "axis": "h",
    "line": 12,
    "length": 3,
    "speed": 2,
    "range": [
     2,
     10
    ],
    "startPos": 3,
    "startDir": -1
   },
   {
    "axis": "v",
    "line": 12,
    "length": 3,
    "speed": 1.6,
    "range": [
     2,
     10
    ],
    "startPos": 6,
    "startDir": -1
   },
   {
    "axis": "v",
    "line": 0,
    "length": 3,
    "speed": 1.8,
    "range": [
     2,
     10
    ],
    "startPos": 8,
    "startDir": 1
   }
  ]
 },
 {
  "name": "The Gauntlet",
  "gridWidth": 14,
  "gridHeight": 14,
  "obstacles": [
   {
    "x": 1,
    "y": 11,
    "type": "rock"
   },
   {
    "x": 12,
    "y": 6,
    "type": "pier"
   },
   {
    "x": 4,
    "y": 5,
    "type": "rock"
   },
   {
    "x": 7,
    "y": 7,
    "type": "buoy"
   },
   {
    "x": 8,
    "y": 1,
    "type": "rock"
   },
   {
    "x": 2,
    "y": 2,
    "type": "rock"
   },
   {
    "x": 8,
    "y": 5,
    "type": "rock"
   }
  ],
  "ships": [
   {
    "x": 4,
    "y": 11,
    "direction": "E",
    "length": 2
   },
   {
    "x": 3,
    "y": 10,
    "direction": "W",
    "length": 3
   },
   {
    "x": 4,
    "y": 4,
    "direction": "N",
    "length": 1
   },
   {
    "x": 1,
    "y": 4,
    "direction": "W",
    "length": 2
   },
   {
    "x": 3,
    "y": 4,
    "direction": "S",
    "length": 1
   },
   {
    "x": 2,
    "y": 12,
    "direction": "W",
    "length": 3
   },
   {
    "x": 8,
    "y": 2,
    "direction": "E",
    "length": 2
   },
   {
    "x": 1,
    "y": 3,
    "direction": "E",
    "length": 4
   },
   {
    "x": 5,
    "y": 6,
    "direction": "S",
    "length": 2
   },
   {
    "x": 8,
    "y": 6,
    "direction": "S",
    "length": 4
   },
   {
    "x": 10,
    "y": 8,
    "direction": "E",
    "length": 2
   },
   {
    "x": 3,
    "y": 5,
    "direction": "W",
    "length": 1
   },
   {
    "x": 10,
    "y": 4,
    "direction": "N",
    "length": 4
   },
   {
    "x": 3,
    "y": 11,
    "direction": "S",
    "length": 1
   },
   {
    "x": 2,
    "y": 8,
    "direction": "E",
    "length": 3
   },
   {
    "x": 11,
    "y": 2,
    "direction": "E",
    "length": 1
   },
   {
    "x": 7,
    "y": 3,
    "direction": "N",
    "length": 3
   },
   {
    "x": 11,
    "y": 1,
    "direction": "E",
    "length": 2
   },
   {
    "x": 3,
    "y": 9,
    "direction": "E",
    "length": 4
   },
   {
    "x": 9,
    "y": 10,
    "direction": "S",
    "length": 3
   },
   {
    "x": 12,
    "y": 2,
    "direction": "N",
    "length": 2
   },
   {
    "x": 3,
    "y": 6,
    "direction": "S",
    "length": 1
   },
   {
    "x": 11,
    "y": 12,
    "direction": "S",
    "length": 1
   },
   {
    "x": 7,
    "y": 11,
    "direction": "S",
    "length": 2
   },
   {
    "x": 5,
    "y": 1,
    "direction": "W",
    "length": 3
   },
   {
    "x": 5,
    "y": 8,
    "direction": "S",
    "length": 1
   },
   {
    "x": 3,
    "y": 2,
    "direction": "E",
    "length": 3
   },
   {
    "x": 9,
    "y": 4,
    "direction": "S",
    "length": 1
   },
   {
    "x": 9,
    "y": 6,
    "direction": "S",
    "length": 3
   },
   {
    "x": 11,
    "y": 5,
    "direction": "N",
    "length": 3
   },
   {
    "x": 10,
    "y": 11,
    "direction": "E",
    "length": 2
   },
   {
    "x": 12,
    "y": 9,
    "direction": "S",
    "length": 3
   },
   {
    "x": 5,
    "y": 5,
    "direction": "N",
    "length": 1
   },
   {
    "x": 12,
    "y": 12,
    "direction": "W",
    "length": 1
   }
  ],
  "patrols": [
   {
    "axis": "h",
    "line": 0,
    "length": 4,
    "speed": 1.7,
    "range": [
     2,
     11
    ],
    "startPos": 2,
    "startDir": -1
   },
   {
    "axis": "h",
    "line": 13,
    "length": 4,
    "speed": 1.6,
    "range": [
     2,
     11
    ],
    "startPos": 4,
    "startDir": 1
   },
   {
    "axis": "v",
    "line": 13,
    "length": 3,
    "speed": 1.9,
    "range": [
     2,
     11
    ],
    "startPos": 8,
    "startDir": -1
   },
   {
    "axis": "v",
    "line": 0,
    "length": 3,
    "speed": 1.5,
    "range": [
     2,
     11
    ],
    "startPos": 2,
    "startDir": -1
   }
  ]
 },
 {
  "name": "Quiet Defiance",
  "gridWidth": 14,
  "gridHeight": 14,
  "obstacles": [
   {
    "x": 3,
    "y": 7,
    "type": "rock"
   },
   {
    "x": 7,
    "y": 9,
    "type": "rock"
   },
   {
    "x": 9,
    "y": 6,
    "type": "pier"
   },
   {
    "x": 5,
    "y": 12,
    "type": "buoy"
   },
   {
    "x": 7,
    "y": 12,
    "type": "pier"
   },
   {
    "x": 1,
    "y": 11,
    "type": "rock"
   },
   {
    "x": 12,
    "y": 5,
    "type": "rock"
   },
   {
    "x": 3,
    "y": 5,
    "type": "rock"
   }
  ],
  "ships": [
   {
    "x": 3,
    "y": 3,
    "direction": "W",
    "length": 2
   },
   {
    "x": 4,
    "y": 6,
    "direction": "N",
    "length": 3
   },
   {
    "x": 11,
    "y": 3,
    "direction": "E",
    "length": 2
   },
   {
    "x": 7,
    "y": 2,
    "direction": "W",
    "length": 1
   },
   {
    "x": 8,
    "y": 12,
    "direction": "E",
    "length": 3
   },
   {
    "x": 2,
    "y": 5,
    "direction": "W",
    "length": 1
   },
   {
    "x": 11,
    "y": 4,
    "direction": "N",
    "length": 2
   },
   {
    "x": 3,
    "y": 10,
    "direction": "W",
    "length": 3
   },
   {
    "x": 1,
    "y": 12,
    "direction": "W",
    "length": 4
   },
   {
    "x": 6,
    "y": 8,
    "direction": "S",
    "length": 4
   },
   {
    "x": 5,
    "y": 5,
    "direction": "N",
    "length": 4
   },
   {
    "x": 1,
    "y": 6,
    "direction": "W",
    "length": 3
   },
   {
    "x": 1,
    "y": 9,
    "direction": "N",
    "length": 2
   },
   {
    "x": 10,
    "y": 1,
    "direction": "W",
    "length": 2
   },
   {
    "x": 11,
    "y": 9,
    "direction": "E",
    "length": 1
   },
   {
    "x": 2,
    "y": 11,
    "direction": "E",
    "length": 3
   },
   {
    "x": 2,
    "y": 4,
    "direction": "W",
    "length": 2
   },
   {
    "x": 9,
    "y": 3,
    "direction": "E",
    "length": 1
   },
   {
    "x": 3,
    "y": 1,
    "direction": "W",
    "length": 3
   },
   {
    "x": 8,
    "y": 8,
    "direction": "S",
    "length": 2
   },
   {
    "x": 10,
    "y": 4,
    "direction": "N",
    "length": 3
   },
   {
    "x": 4,
    "y": 4,
    "direction": "W",
    "length": 4
   },
   {
    "x": 1,
    "y": 1,
    "direction": "W",
    "length": 2
   },
   {
    "x": 2,
    "y": 9,
    "direction": "N",
    "length": 2
   },
   {
    "x": 1,
    "y": 2,
    "direction": "N",
    "length": 4
   },
   {
    "x": 8,
    "y": 2,
    "direction": "N",
    "length": 1
   },
   {
    "x": 6,
    "y": 1,
    "direction": "N",
    "length": 1
   },
   {
    "x": 11,
    "y": 2,
    "direction": "W",
    "length": 2
   },
   {
    "x": 6,
    "y": 6,
    "direction": "W",
    "length": 2
   },
   {
    "x": 4,
    "y": 5,
    "direction": "N",
    "length": 1
   },
   {
    "x": 6,
    "y": 2,
    "direction": "S",
    "length": 1
   },
   {
    "x": 8,
    "y": 3,
    "direction": "N",
    "length": 2
   },
   {
    "x": 11,
    "y": 8,
    "direction": "E",
    "length": 1
   },
   {
    "x": 5,
    "y": 3,
    "direction": "E",
    "length": 2
   },
   {
    "x": 3,
    "y": 8,
    "direction": "S",
    "length": 2
   },
   {
    "x": 4,
    "y": 2,
    "direction": "W",
    "length": 1
   }
  ],
  "patrols": [
   {
    "axis": "h",
    "line": 0,
    "length": 4,
    "speed": 1.9,
    "range": [
     2,
     11
    ],
    "startPos": 2,
    "startDir": -1
   },
   {
    "axis": "h",
    "line": 13,
    "length": 3,
    "speed": 2.1,
    "range": [
     2,
     11
    ],
    "startPos": 5,
    "startDir": 1
   },
   {
    "axis": "v",
    "line": 13,
    "length": 4,
    "speed": 1.6,
    "range": [
     2,
     11
    ],
    "startPos": 3,
    "startDir": 1
   },
   {
    "axis": "v",
    "line": 0,
    "length": 3,
    "speed": 1.8,
    "range": [
     2,
     11
    ],
    "startPos": 9,
    "startDir": -1
   }
  ]
 },
 {
  "name": "Strait of Hormuz",
  "gridWidth": 14,
  "gridHeight": 14,
  "obstacles": [
   {
    "x": 6,
    "y": 4,
    "type": "rock"
   },
   {
    "x": 12,
    "y": 12,
    "type": "buoy"
   },
   {
    "x": 10,
    "y": 4,
    "type": "pier"
   },
   {
    "x": 8,
    "y": 4,
    "type": "rock"
   },
   {
    "x": 7,
    "y": 11,
    "type": "rock"
   },
   {
    "x": 11,
    "y": 8,
    "type": "rock"
   },
   {
    "x": 3,
    "y": 1,
    "type": "rock"
   },
   {
    "x": 7,
    "y": 5,
    "type": "pier"
   }
  ],
  "ships": [
   {
    "x": 7,
    "y": 7,
    "direction": "E",
    "length": 3
   },
   {
    "x": 9,
    "y": 1,
    "direction": "N",
    "length": 4
   },
   {
    "x": 12,
    "y": 9,
    "direction": "N",
    "length": 3
   },
   {
    "x": 2,
    "y": 9,
    "direction": "S",
    "length": 4
   },
   {
    "x": 3,
    "y": 2,
    "direction": "W",
    "length": 4
   },
   {
    "x": 4,
    "y": 4,
    "direction": "S",
    "length": 4
   },
   {
    "x": 7,
    "y": 1,
    "direction": "N",
    "length": 1
   },
   {
    "x": 9,
    "y": 9,
    "direction": "W",
    "length": 2
   },
   {
    "x": 6,
    "y": 5,
    "direction": "S",
    "length": 2
   },
   {
    "x": 9,
    "y": 6,
    "direction": "S",
    "length": 1
   },
   {
    "x": 1,
    "y": 6,
    "direction": "S",
    "length": 4
   },
   {
    "x": 6,
    "y": 8,
    "direction": "W",
    "length": 3
   },
   {
    "x": 5,
    "y": 11,
    "direction": "S",
    "length": 1
   },
   {
    "x": 3,
    "y": 10,
    "direction": "E",
    "length": 3
   },
   {
    "x": 7,
    "y": 12,
    "direction": "W",
    "length": 3
   },
   {
    "x": 1,
    "y": 3,
    "direction": "W",
    "length": 1
   },
   {
    "x": 1,
    "y": 1,
    "direction": "W",
    "length": 2
   },
   {
    "x": 11,
    "y": 2,
    "direction": "E",
    "length": 2
   },
   {
    "x": 7,
    "y": 3,
    "direction": "W",
    "length": 1
   },
   {
    "x": 10,
    "y": 6,
    "direction": "E",
    "length": 1
   },
   {
    "x": 12,
    "y": 4,
    "direction": "N",
    "length": 3
   },
   {
    "x": 10,
    "y": 11,
    "direction": "S",
    "length": 2
   },
   {
    "x": 12,
    "y": 7,
    "direction": "E",
    "length": 1
   },
   {
    "x": 3,
    "y": 3,
    "direction": "W",
    "length": 2
   },
   {
    "x": 8,
    "y": 3,
    "direction": "E",
    "length": 1
   },
   {
    "x": 3,
    "y": 12,
    "direction": "W",
    "length": 4
   },
   {
    "x": 11,
    "y": 9,
    "direction": "S",
    "length": 2
   },
   {
    "x": 3,
    "y": 4,
    "direction": "S",
    "length": 4
   },
   {
    "x": 9,
    "y": 5,
    "direction": "E",
    "length": 1
   },
   {
    "x": 5,
    "y": 7,
    "direction": "S",
    "length": 2
   },
   {
    "x": 10,
    "y": 7,
    "direction": "S",
    "length": 2
   },
   {
    "x": 6,
    "y": 9,
    "direction": "S",
    "length": 3
   },
   {
    "x": 7,
    "y": 10,
    "direction": "E",
    "length": 1
   },
   {
    "x": 8,
    "y": 1,
    "direction": "N",
    "length": 2
   },
   {
    "x": 4,
    "y": 1,
    "direction": "E",
    "length": 2
   },
   {
    "x": 1,
    "y": 5,
    "direction": "W",
    "length": 2
   },
   {
    "x": 7,
    "y": 9,
    "direction": "W",
    "length": 2
   },
   {
    "x": 8,
    "y": 5,
    "direction": "S",
    "length": 1
   },
   {
    "x": 2,
    "y": 2,
    "direction": "N",
    "length": 1
   },
   {
    "x": 7,
    "y": 2,
    "direction": "W",
    "length": 1
   }
  ],
  "patrols": [
   {
    "axis": "h",
    "line": 0,
    "length": 4,
    "speed": 2,
    "range": [
     2,
     11
    ],
    "startPos": 2,
    "startDir": 1
   },
   {
    "axis": "h",
    "line": 13,
    "length": 4,
    "speed": 1.7,
    "range": [
     2,
     11
    ],
    "startPos": 3,
    "startDir": 1
   },
   {
    "axis": "v",
    "line": 13,
    "length": 3,
    "speed": 1.9,
    "range": [
     2,
     11
    ],
    "startPos": 7,
    "startDir": -1
   },
   {
    "axis": "v",
    "line": 0,
    "length": 3,
    "speed": 1.6,
    "range": [
     2,
     11
    ],
    "startPos": 3,
    "startDir": 1
   }
  ]
 }
];
